### ISSUE TITLE
🆕 NEW : Right Sidebar design 

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#104]
Components to be made : 
- Calendar 
- Notes Card

![Right Side bar design](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/e03b5920-e029-4de4-a29e-a5dc541e0e4d)

**Comment by dhrumishah** [comment]
Hey! I would like to work on this

**Comment by PayalPadmalyaPrusty** [comment]
@PiyushKalyanpy I want to contribute.Please assign me
