### ISSUE TITLE
Footer Links are not active.

### ISSUE THREAD

**Issue by prernadabi23** [PiyushKalyanpy/GyanaGuru#115]
All the Quick Links take the user to the home page not to their respective pages.

I would like to take this issue under GSSOC'23.

![Screenshot from 2023-05-22 14-08-24](https://github.com/PiyushKalyanpy/GyanaGuru/assets/104578155/a71fed01-a23a-4767-811d-1fd866ed8b8f)

**Comment by PiyushKalyanpy** [comment]
Sure, go ahead.
