### ISSUE TITLE
The images in the website used are not relative.

### ISSUE THREAD

**Issue by prernadabi23** [PiyushKalyanpy/GyanaGuru#116]
The images used in the website are not related to the website's overall theme and don't convey the real message that the website is used for education.

![Screenshot from 2023-05-22 14-14-22](https://github.com/PiyushKalyanpy/GyanaGuru/assets/104578155/9dc4b725-2898-4ad3-9645-87ae590f487f)

![Screenshot from 2023-05-22 14-14-19](https://github.com/PiyushKalyanpy/GyanaGuru/assets/104578155/ca816feb-086b-4ae2-8d5b-593039be332a)

We should use images related to education that would be more suitable for the theme of the website.
I would like to take this issue under GSSOC'23.

**Comment by PiyushKalyanpy** [comment]
please show some samples of images.

**Comment by prernadabi23** [comment]
We can show images related to our services that would be beneficial, that we provide services that are not limited to age or specific topics and we provide a range of sources.

![Screenshot from 2023-05-29 22-03-01](https://github.com/PiyushKalyanpy/GyanaGuru/assets/104578155/abc99306-d891-4cd5-806f-71f7923b53d8)

@PiyushKalyanpy

**Comment by PiyushKalyanpy** [comment]
For now we have decided not to update the images.
