### ISSUE TITLE
Add middleware in Next.js for redirecting to login page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#12]
### :memo: Description
Currently, there is no middleware in our Next.js application that checks the value of the `login` cookie variable. We need to add a middleware that will redirect the user to the login page if the `login` cookie is false.

### :bulb: Proposed Solution
We can create a middleware function in `_middleware` file, that will be called on every page request. This function will check the value of the `login` cookie, and if it is false, it will redirect the user to the login page.

### :point_right: Steps to create a middleware 

- Create a `middleware.ts` file at the same level as  pages (in the root directory)
- Export a middleware function from the `middleware.ts `file:

You can refer this page for more information on [Next.js Middleware](https://nextjs.org/docs/advanced-features/middleware)  and for [Cookies](https://nextjs.org/docs/advanced-features/middleware#using-cookies)

If you need help with this issue , feel free to ask for assistance 💬.

**Comment by JBic9832** [comment]
I believe this is a solution:
```
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function middleware(request: NextRequest) {
    const cookiesStore = request.cookies;
    const isLoggedIn = cookiesStore.get("login");
    if (!isLoggedIn) {
        return NextResponse.redirect(new URL("/login"));
    }
}
```
Forgive me if I am wrong.

**Comment by PiyushKalyanpy** [comment]
Thankyou for your contribution @JBic9832 🙌
