### ISSUE TITLE
Add Smooth scroll

### ISSUE THREAD

**Issue by suryanshsoni120** [PiyushKalyanpy/GyanaGuru#121]
Adding a smooth scroll once the user wants to go to a particular section will improve the user experience. Can you please assign me this issue under GSSOC'23?

**Comment by sirajlekhak** [comment]
I am eager to contribute as a valuable team member and demonstrate my skills in GSSoC'23. If you would kindly assign me an issue, I would be delighted to work on it and showcase my abilities effectively within the program.

**Comment by PiyushKalyanpy** [comment]
What are the updates??

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
