### ISSUE TITLE
Design Mobile view for App

### ISSUE THREAD

**Issue by muhammedanaskhan** [PiyushKalyanpy/GyanaGuru#123]
Can I work on desiging mobile view and also fix tilte pading below 1100px screen width
![gyanaview](https://github.com/PiyushKalyanpy/GyanaGuru/assets/72510634/80ff344d-35c7-4f13-8ad1-7f3f1eeb24f8)

**Comment by sirajlekhak** [comment]
I am eager to contribute as a valuable team member and demonstrate my skills in GSSoC'23. If you would kindly assign me an issue, I would be delighted to work on it and showcase my abilities effectively within the program.

**Comment by PiyushKalyanpy** [comment]
What are the updates.?

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
