### ISSUE TITLE
Relevant images and content organization

### ISSUE THREAD

**Issue by charu210703** [PiyushKalyanpy/GyanaGuru#124]
I wish replace the existing images with more relevant ones and also want to align the content of the cards uniformly.

**Comment by charu210703** [comment]
Please assign this task to me under GSSOC'23.

**Comment by PiyushKalyanpy** [comment]
Make sure that the images/illustrations should match the current theme.

**Comment by charu210703** [comment]
yeah sure

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me.I have a good knowledge of UI as well

**Comment by PiyushKalyanpy** [comment]
@charu210703 @charu210703 please show some samples.

**Comment by charu210703** [comment]
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/33421514/d0e35727-241a-442d-8b24-c49ac72db819)
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/33421514/299bcdcf-e19c-4b92-bfac-042517330f3e)
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/33421514/0586b0d5-ef0b-4043-8b5d-66a3eb3fe868)
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/33421514/1b1670f9-41c7-4025-8b3a-d4778a87d968)
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/33421514/f59a687b-89f6-4c81-a1cd-baef811786a5)
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/33421514/133bf7e9-dffa-4592-b08c-2ff8416ad500)

**Comment by PiyushKalyanpy** [comment]
We have planned, not to update the current images.
