### ISSUE TITLE
Fix extra Padding in Explore Courses Button

### ISSUE THREAD

**Issue by muhammedanaskhan** [PiyushKalyanpy/GyanaGuru#126]
![btn](https://github.com/PiyushKalyanpy/GyanaGuru/assets/72510634/036733d7-ae48-4861-adf2-068c6685b27a)

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
