### ISSUE TITLE
Adding contact form validation

### ISSUE THREAD

**Issue by SubhamB2003** [PiyushKalyanpy/GyanaGuru#131]
Hey, I want to add contact form validation and after clicking the submit button it loads an infinite time so I also fixed this issue.

Please assign it to me under @GSSOC'23

**Comment by PiyushKalyanpy** [comment]
Thankyou for your interest, how you have planned to resolve this issue ?

**Comment by PiyushKalyanpy** [comment]
Closing this issue, as it is solved.
