### ISSUE TITLE
Update CONTRIBUTIONS GUIDE.md

### ISSUE THREAD

**Issue by shanvijha30** [PiyushKalyanpy/GyanaGuru#132]
Update the Contributing Guideline documentation.

**Comment by shanvijha30** [comment]
@PiyushKalyanpy Could you please assign me this issue under GSSOC 23
Thank you!

**Comment by PiyushKalyanpy** [comment]
What updates you have planned ??

**Comment by shanvijha30** [comment]
I will explain each step in more detail and would provide more information such that contributor would easily understand the steps of how to contribute and would even provide additional resources to which they can refer.

**Comment by PiyushKalyanpy** [comment]
@shanvijha30 I have assigned you the issue.

**Comment by Snigdha2712** [comment]
Please assign this issue to me. I would like to work on it @PiyushKalyanpy

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
