### ISSUE TITLE
Hover effect to footer section

### ISSUE THREAD

**Issue by Ajay4486** [PiyushKalyanpy/GyanaGuru#137]
Footer section can be made more attractive by adding some great hovering effects ,
please assigned this issue to me under GSSOC'23 .
![Screenshot 2023-05-23 143121](https://github.com/PiyushKalyanpy/GyanaGuru/assets/106949690/b0fd48cc-fb44-436e-bd98-d5994c67b5ab)

**Comment by PiyushKalyanpy** [comment]
Yeah, we can add some good hover effects, 
assigning this issue to you

**Comment by Visbhavesh** [comment]
Please assign me this task under GSSOC 23

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
