### ISSUE TITLE
UI of the footer 

### ISSUE THREAD

**Issue by ShivangRawat30** [PiyushKalyanpy/GyanaGuru#139]
We can change the UI of the footer to make it look more professional and collaborative.

**Comment by PiyushKalyanpy** [comment]
What are the changes you would like to do??

**Comment by ShivangRawat30** [comment]
@PiyushKalyanpy we can add the logo of the website at the bottom too, at the left side and keep the other data on the right side of the page
<img width="1364" alt="Screenshot 2023-05-25 at 3 12 38 PM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/114716075/0ca8beca-7703-4be3-97eb-7efd8659d822">
like this screen shot, we can do some changes

**Comment by PiyushKalyanpy** [comment]
That's great, @ShivangRawat30 I am assigning this issue to you.

**Comment by pjyoti121** [comment]
please assign me this issue

**Comment by PiyushKalyanpy** [comment]
What are the updates @ShivangRawat30

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
