### ISSUE TITLE
Add padding in button to make it look better

### ISSUE THREAD

**Issue by muhammedanaskhan** [PiyushKalyanpy/GyanaGuru#142]
I see if we can add bit padding to he left and right of the Send Message it'd be a nice idea..
![send](https://github.com/PiyushKalyanpy/GyanaGuru/assets/72510634/27a9c3c6-540b-4f66-9499-d1e31ae1f262)

PLease assign me this task to work on

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by PiyushKalyanpy** [comment]
@muhammedanaskhan What are the updates??

**Comment by muhammedanaskhan** [comment]
Am not working on this unfortunately, sorry for it please assign to anyone else interested.

**Comment by bhoomikhurana** [comment]
I would like to work upon this issue!

**Comment by bhoomikhurana** [comment]
Kindly revert!

**Comment by PiyushKalyanpy** [comment]
Ok @bhoomikhurana, i have assigned this issue to you.
