### ISSUE TITLE
📁 Reorganize Project Files: Enhance File Structure for Improved Development Experience

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#15]
## Goal 
🎯 The goal of this issue is to refactor and reorganize the file structure of the project to improve code maintainability and development efficiency.

# Tasks:
  - Evaluate current file structure, identify areas for improvement
  - Create proposed folder structure following industry-standard conventions
  - Move files and directories into new structure, update dependencies
  - Test refactored file structure for smooth building and running
  - Document new structure in README, provide folder overview
  - Create pull request with updated file structure for review and merge

###  Expected Outcome: 
A well-organized file system for easier navigation, file location, and efficient collaboration. Streamlined development process and improved code maintainability.

### Skills Required: 
Next.js familiarity, understanding of file organization and best practices.

### Additional Information: 
If you're new to file structure refactoring or need guidance, we're here to support you. Let's create a more organized and efficient project together! Claim this issue to contribute. 💪

Feel free to claim this issue and contribute to the project's file structure reorganization. Your efforts in enhancing the organization and maintainability are appreciated. Let's work together to create a better development experience! 🚀

**Comment by AbhishekPSingh07** [comment]
Hii I am a GSSoC'23 Contributor I would like to contribute to this issue but I am new to this File Structuring

**Comment by SakshiShah29** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by ninjahattori21** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by PiyushKalyanpy** [comment]
Have you updated the files?? @SakshiShah29 @AbhishekPSingh07

**Comment by SakshiShah29** [comment]
Hey @PiyushKalyanpy , I am working on it.

**Comment by PiyushKalyanpy** [comment]
Please pull the code before you push and resolve the errors

**Comment by lalitmee** [comment]
@PiyushKalyanpy, I think we should have a discussion first about what kind of folder structure is @SakshiShah29 suggesting.

That would be a more right approach. Instead of directly working on it lets us first finalize the structure after reviewing it thoroughly.

@SakshiShah29, you can use tools such as [excalidraw](https://excalidraw.com/) or [draw.io](https://draw.io) and share the screenshots or the links here.
