### ISSUE TITLE
feat: login as guest

### ISSUE THREAD

**Issue by Jyotipal29** [PiyushKalyanpy/GyanaGuru#150]
Here user has to type credentials manually . i want to implement login as guest  feature which will make user login with just one click .
![gyanguru](https://github.com/PiyushKalyanpy/GyanaGuru/assets/76580894/1646cac0-842e-45b5-8cd9-fc3d319500ea)

**Comment by Jyotipal29** [comment]
please assing this issue to me

**Comment by PiyushKalyanpy** [comment]
What are the updates??

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
