### ISSUE TITLE
feature/scroll-to-the-top button

### ISSUE THREAD

**Issue by mohitparmar1** [PiyushKalyanpy/GyanaGuru#157]
hey! I want to implement a scroll-to-the-top button that navigates the user to the top of the website.
assign this issue to me, if no one raised the issue or pr:)

**Comment by PiyushKalyanpy** [comment]
Hey @mohitparmar1 thankyou for your interest and suggestions. This issue is assigned to someone else so we cannot assign it to you.

**Comment by mohitparmar1** [comment]
Thanks piyush for your kind response and if any issue available, I'll like to work under Gssoc!
