### ISSUE TITLE
Adding Alerts on Login Page

### ISSUE THREAD

**Issue by Hemant2335** [PiyushKalyanpy/GyanaGuru#159]
Adding alerts on the login page too

Please assign it to me under GSSOC'23

Thank you

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by PiyushKalyanpy** [comment]
What are the updates?? If you have made a pull request, please refer this issue in description of pr.

**Comment by Hemant2335** [comment]
I have tried many methods but i think asking you would be the best  , I am not able to solve 

FirebaseError: Firebase: Error (auth/invalid-api-key). this error , I don't if this is only bothering me please help

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
