### ISSUE TITLE
SignUp with Google option is not working 

### ISSUE THREAD

**Issue by Akanksha-202** [PiyushKalyanpy/GyanaGuru#16]
Please assign this issue to me under GSSOC'23 label

**Comment by PiyushKalyanpy** [comment]
Thank you for expressing your interest in working on this issue! I have assigned this issue to you.

**Comment by rhithesh** [comment]
@PiyushKalyanpy  is this fix fine.

`import { ButtonWithImage } from "@/Components/components";
import { useState } from "react";
import { useRouter } from "next/router";
import { CoursesContext } from "../context/CoursesContext";
import { useContext } from "react";

const SignUp = () => {
  const router = useRouter();
  const [user, setUser] = useState({
    email: "",
    password: "",
    confirmPassword: "",
  });
  const [showPassword, setShowPassword] = useState(false);
  const showPasswordToggle = () => {
    setShowPassword(!showPassword);
  };
  const moveToSignIn = () => {
    router.push("/login");
  };
  const { loginUser, logoutUser }:any = useContext(CoursesContext);


  return (
    <div className="flex w-full h-screen bg-gray-200 ">
      <div className="flex flex-col w-10/12 md:w-8/12 lg:w-1/4 bg-white rounded-lg h-fit m-auto min-h-1/4 p-4 ">
        <div className="flex flex-col space-y-8 items-center ">
          {/* logo with title */}
          {/* <div className="flex flex-row items-center space-x-4 ">
            <img src="/logo.svg" alt="logo" width={40} height={40} />

            <h1 className="text-md font-semibold ">GyanaGuru</h1>
          </div> */}

          {/* login heading and text */}
          <div className="flex w-full px-2 flex-col mt-8 space-y-2 ">
            <h3 className="text-3xl font-semibold ">Sign Up</h3>
            <h4 className="flex">Welcome to Gyana Guru. </h4>
          </div>

          {/* login form */}
          <div className="flex flex-col space-y-4 w-full mx-4 ">
            <ButtonWithImage onClick ={()=>loginUser()}
              buttonName="Continue with Google"
              icon="/images/google.svg"
            />

            {/* make or with divider */}
            <div className="flex flex-row space-x-4 my-4 items-center">
              <hr className="w-full border-gray-300" />
              <h4 className="font-medium text-zinc-500">or</h4>
              <hr className="w-full border-gray-300" />
            </div>

            {/* login with email and password */}
            <div className="flex flex-col space-y-4">
              {/* email */}
              <input
                type="email"
                placeholder="Email"
                value={user.email}
                onChange={(e) => setUser({ ...user, email: e.target.value })}
                className="border border-gray-300 rounded-lg p-2 focus:outline-none focus:border-2 focus:border-black"
              />
              {/* password */}
              <div className="flex w-full space-x-2">
                <input
                  type={showPassword ? "text" : "password"}
                  placeholder="Password"
                  value={user.password}
                  onChange={(e) =>
                    setUser({ ...user, password: e.target.value })
                  }
                  className="w-full border focus:outline-none focus:border-2 focus:border-black border-gray-300 rounded-lg p-2"
                />
                
              </div>
              {/* confirm password */}
              <div className="flex w-full space-x-2">
                <input
                  type={showPassword ? "text" : "password"}
                  placeholder="Confirm password"
                  value={user.confirmPassword}
                  onChange={(e) =>
                    setUser({ ...user, confirmPassword: e.target.value })
                  }
                  className="w-full border focus:outline-none focus:border-2 focus:border-black border-gray-300 rounded-lg p-2"
                />
                <div
                  className="flex items-center text-zinc-500 border focus:outline-none focus:border-2 focus:border-black border-gray-300 rounded-lg p-2  "
                  onClick={() => showPasswordToggle()}
                >
                  <span className="material-icons-outlined ">
                    {showPassword ? "visibility" : "visibility_off"}
                  </span>
                </div>
              </div>

              
            </div>

            {/* login button */}
            <div className="flex flex-row space-x-4 py-4 transition hover:scale-[1.02]">
              <button className="bg-black text-white rounded-lg p-2 w-full">
                Sign Up 
              </button>
            </div>

            {/* Create Account */}
            <div className="flex flex-col items-center mt-4 text-sm justify-between">
              <p className="w-fit text-slate-600">Already have an account</p>
              <p
                onClick={() => moveToSignIn()}
                className="w-fit text-black hover:underline cursor-pointer"
              >
                Sign In to you account
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SignUp;

`

**Comment by rhithesh** [comment]
![fix](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115660976/a87e0367-40ac-4038-8bc7-044137061682)

**Comment by Akanksha-202** [comment]
> 

I have created a PR for it!
Kindly review it and merge :)

**Comment by Akanksha-202** [comment]
> ![fix](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115660976/a87e0367-40ac-4038-8bc7-044137061682)
> 
> @PiyushKalyanpy @Akanksha-202  hi this fix worked can I do a pr?

Hey!
I have already created a PR for this.

**Comment by rhithesh** [comment]
okay @PiyushKalyanpy
