### ISSUE TITLE
Fix links of Twitter and LinkedIn in the footer under community section

### ISSUE THREAD

**Issue by dakshsinghrathore** [PiyushKalyanpy/GyanaGuru#164]
![Screenshot 2023-05-25 at 10-34-10 404 This page could not be found](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115932772/21259411-3781-4a90-bf58-5cb90530518c)

Hey @PiyushKalyanpy can you please assign this issue to me ? I will fix the links, can you also comment out the URLs of your twitter and linkedIn pages !!✌️

**Comment by PiyushKalyanpy** [comment]
What you have planned to resolve this??

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
