### ISSUE TITLE
Want to change the FAQ page to a better UI

### ISSUE THREAD

**Issue by Lobi29** [PiyushKalyanpy/GyanaGuru#167]
### **Figma Design 👍🏻** 

![21](https://github.com/PiyushKalyanpy/GyanaGuru/assets/108052802/aef52914-ae00-48df-9b6e-7d6d5b0ccc19)

Here I am attaching the contact form along with FAQ section such that 
if user need more help then user can easily contact with **GyanaGuru**

please assign this task to me under @GSSOC2023

**Comment by PiyushKalyanpy** [comment]
⚡ That's Great  @Lobi29, I am assigning this issue to you.

**Comment by PiyushKalyanpy** [comment]
What are the updates??

**Comment by PiyushKalyanpy** [comment]
Are you working on it , or should we close this issue ??

**Comment by Nishitbaria** [comment]
hey @PiyushKalyanpy   please assign me to this issue I can do this in one day
