### ISSUE TITLE
Enhance: Cards above the our services section. 

### ISSUE THREAD

**Issue by Pragati-3003** [PiyushKalyanpy/GyanaGuru#173]
I would like to modify the UI of the cards . 
![IMG_20230526_003839](https://github.com/PiyushKalyanpy/GyanaGuru/assets/132778037/ddc2c16e-857f-4823-9abb-86602b1e4b3d)
So, please assign this issue to me under GSSOC'23.

**Comment by PiyushKalyanpy** [comment]
Hey @Pragati-3003 what you would like to change in this design, please share the screenshot of the new design.
