### ISSUE TITLE
Enhance : Ui of cards below whi choose us section. 

### ISSUE THREAD

**Issue by Pragati-3003** [PiyushKalyanpy/GyanaGuru#174]
I would like to change the UI of card also would like to add some hover effects. 
![IMG_20230526_003853](https://github.com/PiyushKalyanpy/GyanaGuru/assets/132778037/708c4683-8d3a-4c5d-b67e-8f1ba89087dd)
So,please assign this issue to me under GSSOC'23.

**Comment by PiyushKalyanpy** [comment]
Please specify what do you want to change and please show the ui that you want to add so that we would not discard your pull request.
