### ISSUE TITLE
Enhance: Our services button. 

### ISSUE THREAD

**Issue by Pragati-3003** [PiyushKalyanpy/GyanaGuru#175]
I would like to change the button to make them more attractive by adding some cool hover effects. 
![IMG_20230526_004655](https://github.com/PiyushKalyanpy/GyanaGuru/assets/132778037/2eff3e1a-70eb-4907-9d22-3c2756062262)
So, please assign this issue to me under GSSOC'23.

**Comment by PiyushKalyanpy** [comment]
Ok but do not change the colors.

**Comment by Pragati-3003** [comment]
okie

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me.I have a good knowledge of UI as well
