### ISSUE TITLE
Fixing the un-conventional highlight in dark mode in various sections of the websites.

### ISSUE THREAD

**Issue by raj3000k** [PiyushKalyanpy/GyanaGuru#178]
![Screenshot 2023-05-26 at 12 14 40 PM](https://github.com/PiyushKalyanpy/GyanaGuru/assets/91799854/a05aec98-e36c-456a-b800-0a821f102e7f)

For ex: here green highlight on whit text, there are even more all around the website.

**Comment by PiyushKalyanpy** [comment]
Ok, @raj3000k 
assigning this task to you.

**Comment by raj3000k** [comment]
Hey can u please merge it 👍 it's already completed days ago @lalitmee  @PiyushKalyanpy .
