### ISSUE TITLE
Dark Mode button

### ISSUE THREAD

**Issue by parasss19** [PiyushKalyanpy/GyanaGuru#182]
The current dark mode button is very basic

### Changes
I can implement the sliding dark mode button 
The below video is my sample work and i will make it more effective for GyanaGuru
I want to work on this issue please assign me 

https://github.com/PiyushKalyanpy/GyanaGuru/assets/101205226/6342b433-17be-4590-838d-d0bcc88d505f

**Comment by parasss19** [comment]
Hi @PiyushKalyanpy Please review my issue once

**Comment by PiyushKalyanpy** [comment]
Hello @parasss19, we have decided not to change the current button design for changing modes.
