### ISSUE TITLE
Navbar hover

### ISSUE THREAD

**Issue by parasss19** [PiyushKalyanpy/GyanaGuru#183]
### Current 
No hover effect on navbar links

### Changes 
I can apply hover effect with transition for better UI

**Comment by parasss19** [comment]
Hii @PiyushKalyanpy Please see my issue once

**Comment by PiyushKalyanpy** [comment]
we already have a hover effect on nav links, what would you like to change??

**Comment by parasss19** [comment]
> we already have a hover effect on nav links, what would you like to change??

Hi @PiyushKalyanpy 

## Issue
In light mode hover effect is visible but in dark mode hover effect is not visible

## Screenshot

https://github.com/PiyushKalyanpy/GyanaGuru/assets/101205226/1fa4e5c8-218a-4963-b815-769754c6eee8

**Comment by parasss19** [comment]
Hi @PiyushKalyanpy Review my issue once

**Comment by PiyushKalyanpy** [comment]
That is already done.
