### ISSUE TITLE
[style]: The call-to-action button on the navbar and the hero page is not consistent.

### ISSUE THREAD

**Issue by jibola2588** [PiyushKalyanpy/GyanaGuru#184]
The two call-to-action buttons have inconsistent designs, which negatively impacts the user experience
![Screenshot (89)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/76418445/dec47b26-8b81-4e0d-9d5c-916588511e04)

**Comment by PiyushKalyanpy** [comment]
Ok you can work on this issue.

**Comment by jibola2588** [comment]
please assign me this issue under GSSOC'23
