### ISSUE TITLE
Improve the About-Us UI Section

### ISSUE THREAD

**Issue by deepeshgupta3257** [PiyushKalyanpy/GyanaGuru#185]
please assign this issue to me under GSSOC'23 I can design a createive footer/ About-Us section

**Comment by PiyushKalyanpy** [comment]
Ok can you please show us your design.

**Comment by deepeshgupta3257** [comment]
Ya sure you can see these designs

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/108192513/655ddd9f-f712-43f6-95ce-ff2f231cde58)

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/108192513/72bfb129-a8e1-4660-ae61-1382e292cfad)

These are the sample if you like them then please assign me this issue under GSSOC'23

**Comment by PiyushKalyanpy** [comment]
Can you create a New About Us page ( which will show the information about Gyanaguru ) and also add one nav link in landing page for about us page ??
