### ISSUE TITLE
Change the card color

### ISSUE THREAD

**Issue by devWonderkind** [PiyushKalyanpy/GyanaGuru#189]
Heyy @PiyushKalyanpy I would like to change the card color in dark mode.
![GG](https://github.com/PiyushKalyanpy/GyanaGuru/assets/110322061/563fe2d5-8157-4807-97af-29a465f7e2e3)

please assign this issue to me under GSSoC'23.

**Comment by SatyamKumar2002** [comment]
I will resolve this issue if you want then assign me this issue.
