### ISSUE TITLE
Missing issue template for Documentation

### ISSUE THREAD

**Issue by DivyanshiNarang** [PiyushKalyanpy/GyanaGuru#192]
Description:

I noticed that the repository does not have an issue template. Having an issue template can greatly improve the clarity and consistency of issue reports, making it easier for contributors and maintainers to understand and address the problems or feature requests effectively.

Here are three templates that I want to include:

Issue Template: This template enables users to create well-structured issue reports by providing sections for a concise title, detailed description, steps to reproduce (if applicable), expected behavior, actual behavior, additional information, and environment details.

Feature Request Template: The feature request template allows users to outline their desired features with clarity, including sections for a clear feature description, expected benefits, and any additional context or information.

Documentation Template: This template facilitates the creation of comprehensive documentation by providing a structured format, including sections for an introduction, usage instructions, examples, and other relevant details.

Please assign this issue to me under GSSoC'23 @PiyushKalyanpy

**Comment by lalitmee** [comment]
Hey @DivyanshiNarang, thanks for the suggestion.

You are right, the templates for all three are really necessary. So you can start creating separate issues for all three templates. Just to have the three different contexts as all three are completely different things.

And I would suggest you look at [this](https://github.com/PiyushKalyanpy/GyanaGuru/pull/186) also. This is a PR by some other contributor for the Feature Request template. I think you can add your comments on the PR if you have any suggestions after looking at the template.

Let us know if you have any queries.

**Comment by lalitmee** [comment]
@DivyanshiNarang, any update on this?

**Comment by DivyanshiNarang** [comment]
I am working on Issue and Documentation template.

**Comment by DivyanshiNarang** [comment]
Please review it sir. @PiyushKalyanpy
