### ISSUE TITLE
add prettier configurations

### ISSUE THREAD

**Issue by lalitmee** [PiyushKalyanpy/GyanaGuru#193]
Prettier formatting using `eslint` is really worth it. No need to manually format your code.

**Comment by rohanmittal1163** [comment]
hey @lalitmee, pls assign me with this issue. I want to contribute in this repo as a GSSOC'23 contributor. I know how to make a .prettierrc file and what to write.

**Comment by lalitmee** [comment]
Hey @rohanmittal1163, thanks for taking the initiative to contribute to this project. I have assigned you for this task. 

Please let us know if you need any kind of help.

And make sure to add the necessary dev dependencies for `eslint` to work with prettier and make the changes in the `.eslintrc` if needed.

**Comment by rohanmittal1163** [comment]
Ok it will be completed by today itself
