### ISSUE TITLE
create a pull request template

### ISSUE THREAD

**Issue by lalitmee** [PiyushKalyanpy/GyanaGuru#194]
Pull request templates are a good way to provide as much info about the Pull request to make the review process easier.

Let's try to add one for ourselves.

**Comment by DSR1729** [comment]
Hey @lalitmee can you please assign this issue to me? I will make the required changes as soon as possible, the pull request template will look sleek and clean  ! ✌️

**Comment by rohanmittal1163** [comment]
Hi sir @lalitmee pull request templates are very useful for every github repo. I clearly know how to make a pull request template with clean things written on it
pls assign this issue to me under GSSOC'23 as a contributor , i would love to contribute here.
Thank you for reading

**Comment by lalitmee** [comment]
Hey @DSR1729, thanks for taking the intiative to contribute to this project. I have assigned you to this issue.

Please let us know if you need any help. I would also suggest to discuss the things we need in the discord channel of this project so that we are all on the same page and you will not have to work on this issue multiple times. So lets first try to come up with some of the important things we want in the Pull Request template.

@rohanmittal1163, I have already assigned you https://github.com/PiyushKalyanpy/GyanaGuru/issues/193. For now you can work on that and @DSR1729 can work on this.

**Comment by DSR1729** [comment]
Hey @lalitmee thank you for assigning #194 to me , have already pinged you on discord !
