### ISSUE TITLE
The section below the navbar disappears on scrolling 

### ISSUE THREAD

**Issue by vishnubansal001** [PiyushKalyanpy/GyanaGuru#195]
Hey , i want to raise the issue about that the section bellow the navbar which is 

![Screenshot (97)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/101445306/c0c4e34b-41ff-4e80-8dab-2bfb7c365172)

disappears some time when we scroll down or scrolls up like 

![Screenshot (98)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/101445306/2d846d8f-38fc-42bc-9f2f-be87466776c1)

I am a GSSOC'23 contributor 
I want to work on this issue please allow me to work on this issue @PiyushKalyanpy

**Comment by lalitmee** [comment]
@vishnubansal001, I am not able to understand the issue. Can you please make a video of the issue and post it here. Till then I will be assigning you this issue and if you think that there are some changes which need to be done. Please raise a PR.

**Comment by ujjawaltyagii** [comment]
@lalitmee I thinking he is considering design of Nav as bug. What i can understand is that he is considering the blur effect of nav bar background on scrolling as bug which is not the case as it's a design !

**Comment by vishnubansal001** [comment]
@ujjawaltyagii  No not that

**Comment by lalitmee** [comment]
@vishnubansal001, can you please elaborate on what is the bug? And if possible please try to explain the bug using some screenshots or a video.

**Comment by vishnubansal001** [comment]
when we are scrolling down on the home page the section or can say a marquee element is disappreaing and when we are scrolling up this is appearing as it is so i am suggesting that this will remain as it is on scrolling even it is up or it is down

**Comment by PiyushKalyanpy** [comment]
@vishnubansal001 we have designed it like this only. So that the user can view the full page view by removing obstruction (marquee element : in this case)
