### ISSUE TITLE
fix `CODE_OF_CONDUCT` file name

### ISSUE THREAD

**Issue by lalitmee** [PiyushKalyanpy/GyanaGuru#196]
Please read this [doc](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) and then make the desired changes to the file.

**Comment by akash19coder** [comment]
@lalitmee Could you please assign me to this issue?

**Comment by akash19coder** [comment]
May be we should make it available in multiple languages.

**Comment by riddhigupta1110** [comment]
> Please read this [doc](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) and then make the desired changes to the file.

I have read the doc and I believe I'll be able to make the desired changes in the file. Please assign me this issue under GSSoC'23.

**Comment by lalitmee** [comment]
@akash19coder, I have assigned you this issue. Sorry @riddhigupta1110, for now, let @akash19coder work on it. You can help with this PR by reviewing it. Till then you can look out for other issues in the project.

**Comment by riddhigupta1110** [comment]
> @akash19coder, I have assigned you this issue. Sorry @riddhigupta1110, for now, let @akash19coder work on it. You can help with this PR by reviewing it. Till then you can look out for other issues in the project.

Sure, no worries

**Comment by akash19coder** [comment]
@riddhigupta1110 you can work on  Contributing Guide. There's an issue open.

**Comment by vk20july** [comment]
@akash19coder sir i want to work on this issue under gssoc'23
