### ISSUE TITLE
fix `CONTRIBUTING` file name

### ISSUE THREAD

**Issue by lalitmee** [PiyushKalyanpy/GyanaGuru#197]
Please read this [doc](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) and then make the desired changes.

**Comment by akash19coder** [comment]
@lalitmee I would like to work on this on as well

**Comment by bhoomikhurana** [comment]
pls assign this task to me.I'd like to work upon it

**Comment by arunavabasu-03** [comment]
I would like to work on this!

**Comment by riddhigupta1110** [comment]
I have read the doc and would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by tmsagarofficial** [comment]
@PiyushKalyanpy @lalitmee I have rad the documentation and would love to work on this issue. Pls, assign this to me when possible.

**Comment by Sandeep77942** [comment]
I would like to work on this if it's still open.

**Comment by lalitmee** [comment]
@akash19coder, are you still up for working on it?

**Comment by akash19coder** [comment]
I have my sem exams going on right now so I am not working on it.

**Comment by tmsagarofficial** [comment]
> I have my sem exams going on right now so I am not working on it.

So can i work on this issue??
@lalitmee

**Comment by Sandeep77942** [comment]
> @akash19coder, are you still up for working on it?

Please do let me work on it.

**Comment by lalitmee** [comment]
Sure @Sandeep77942. You can start working on it. Assigning it to you.

**Comment by tmsagarofficial** [comment]
@lalitmee hey man I would also like to work on this. I had mentioned this earlier too 😅

**Comment by Sandeep77942** [comment]
> Sure @Sandeep77942. You can start working on it. Assigning it to you.

Do you want me to create a new file CONTRIBUTING.md or just rename CONTRIBUTIONS GUIDE.md, can you please explain the issue clearly
