### ISSUE TITLE
[Bug] : Hover effect in dark theme on nav bar not working

### ISSUE THREAD

**Issue by ujjawaltyagii** [PiyushKalyanpy/GyanaGuru#199]
#### There is a issue in dark theme as when we hover on nav bar we can't see the hover underline effect unlike light theme where this effect is visible.

- Please assign this issue to me so that I can start working on this issue

- I am a gssoc contributor so please add required labels 

https://github.com/PiyushKalyanpy/GyanaGuru/assets/115401171/5f044a58-c2a6-4a5d-8fb7-7e5b03638464

**Comment by ujjawaltyagii** [comment]
@lalitmee

**Comment by ujjawaltyagii** [comment]
@PiyushKalyanpy could you assign this to me ?

**Comment by PiyushKalyanpy** [comment]
Ok sure, i am assigning this issue to you.
