### ISSUE TITLE
Request to Make Logo Clickable in Navbar for Homepage Redirection [GSSOC'23]

### ISSUE THREAD

**Issue by Saurav-Pant** [PiyushKalyanpy/GyanaGuru#20]
Kindly consider making the logo in the navbar clickable, redirecting users to the homepage. This enhancement will improve user experience and provide consistent navigation. Requesting an issue to be created to address this feature request. Thank you for your attention to this matter.
Assign it to me

**Comment by dhrumishah** [comment]
hey! can I work on this?

**Comment by PiyushKalyanpy** [comment]
If you are getting error for Firebase auth API - you can checkout to ```nofirebase``` branch ( for frontend), but for backend you have to generate your own firebase API keys. 
- Go to firebase.com -> create account -> create a new project
- Select web project choose nickname and continue
- copy the API keys and replace them in code

**Comment by Saurav-Pant** [comment]
why did you unassign me? @PiyushKalyanpy
