### ISSUE TITLE
Integrating GItpod in the project

### ISSUE THREAD

**Issue by akash19coder** [PiyushKalyanpy/GyanaGuru#201]
I recommend integrating Gitpod. It will have a lot of advantages like:
1. Faster onboarding of new developers.
2. Cloud-Based Development Environment
3. Instant Setup and Reproducibility

**Comment by lalitmee** [comment]
@PiyushKalyanpy, what do you think about this feature?

**Comment by PiyushKalyanpy** [comment]
@lalitmee Yes we can proceed, with implementing this feature.

**Comment by akash19coder** [comment]
I am sorry for raising the Pull Request without being assigned to it. I actually thought I have been assigned to it 😄
