### ISSUE TITLE
add contributors page 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [PiyushKalyanpy/GyanaGuru#202]
we can add a contributors' page for the GSSOC23  program. I would like to work on this issue. please assign it to me under GSSOC'23

**Comment by lalitmee** [comment]
What do you mean by contributors' page? Can you please explain what all the things you are thinking of adding in there?

**Comment by shivaniyuvrajyadav** [comment]
@lalitmee on the home page there is a card for our contributors. we can add a separate page for that which shows a list of contributors who are contributing to the project

**Comment by PiyushKalyanpy** [comment]
Ok, please go ahead, i am assigning this issue. Please make sure the design is aligned with the project (colors, corner radius, font size and other styles) you can refer - `gyanaguru.vercel.app/course` for card desigs. 

Please show us the screenshot of the design before making PR.

**Comment by shivaniyuvrajyadav** [comment]
hey @PiyushKalyanpy sorry for the delay here is the design of the contributors' page 


https://github.com/PiyushKalyanpy/GyanaGuru/assets/112896644/a0676fc1-b2b8-4fa2-8bb0-85dd2cf1d28d

**Comment by PiyushKalyanpy** [comment]
What are the updates, are you working on it or should we close the issue??

**Comment by shivaniyuvrajyadav** [comment]
> What are the updates, are you working on it or should we close the issue??
I made contributors page but before making pr I just wanted to confirm the design of this page

**Comment by PiyushKalyanpy** [comment]
Ok, please share a screenshot, or the above video is the only design?

**Comment by shivaniyuvrajyadav** [comment]
Yes, please suggest any changes if you want

**Comment by PiyushKalyanpy** [comment]
We are ok with the design, you can create a PR. 
please make sure to push only required files not package or firebase or other files which are not required. Also please refer this issue in the PR.

**Comment by shivaniyuvrajyadav** [comment]
Ok, thank you
