### ISSUE TITLE
Images are needed to be fixed

### ISSUE THREAD

**Issue by Nikita110602** [PiyushKalyanpy/GyanaGuru#206]
Some images are overlapping and needed proper and equal gapping between them . The hovering in the images are missing. The proper design should be needed.

![Screenshot (27)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/111515819/42b98ebc-2493-43e8-b0e6-ea279c4ea20e)
![Screenshot (26)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/111515819/b331c00e-cc8e-448d-ac4b-087076246301)

**Comment by Nikita110602** [comment]
Pls assign me this issue. I want to work on this issue.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time.
