### ISSUE TITLE
The website is not responsive and not for mobile screens

### ISSUE THREAD

**Issue by Nikita110602** [PiyushKalyanpy/GyanaGuru#207]
This website should needed some responsiveness . Should be visible in mobile screens also.
Let me fix this.
![Screenshot (28)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/111515819/1370c1ce-25ae-498d-bcbd-e0b2462f2781)

**Comment by Nikita110602** [comment]
I want to fix this issue. pls assign me this issue.

**Comment by lalitmee** [comment]
@PiyushKalyanpy, is there any reason that the website is not responsive for mobile or do we want to do this now?
