### ISSUE TITLE
Login page need improvement

### ISSUE THREAD

**Issue by HimanshuNarware** [PiyushKalyanpy/GyanaGuru#209]
##Description
I want to improve the design of the login page, the login page is missing some basic styling, and I want to work on this issue kindly assign me this issue.

##Screenshot
![92](https://github.com/PiyushKalyanpy/GyanaGuru/assets/83147410/1aba63f3-b1e3-40aa-99a7-2efdb9fdc4f7)

**Comment by lalitmee** [comment]
@HimanshuNarware, thanks for taking the initiative. 

First of all, there are formatting issues in your issue. Please check this [doc](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

And the screenshot which you have provided, what is that? Are you suggesting that the login page will look something like this or is it currently having some problems which you want to fix? Please mention all these things here.

**Comment by PiyushKalyanpy** [comment]
Hello @HimanshuNarware 👋,
Thankyou for your interest in our project. Please describe more, what changes you would like to do.

**Comment by HimanshuNarware** [comment]
I want to align the text  and give 

> Hello @HimanshuNarware 👋, Thankyou for your interest in our project. Please describe more, what changes you would like to do.

I want to align elements present on the login page like Login, forgot  password, and want to  give different colors(blue and green) to the create account btn so that the  user easily detect the create a new account btn, also the hover effect on the login page is so basic I also want to improve it, and  also one thing we can add email@example.com placeholder which improves the readability of the website

**Comment by PiyushKalyanpy** [comment]
Ok @HimanshuNarware, you can work on this issue.
