### ISSUE TITLE
login/signup page 

### ISSUE THREAD

**Issue by mandliyarajendra11** [PiyushKalyanpy/GyanaGuru#21]
There should be an option to go back to the home page from the login/signup page.

![Screenshot (93)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119125519/9a15d5a6-01ac-4360-9b0a-3d22f66e96c6)
![Screenshot (92)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119125519/82d046b5-d6bf-4f18-9f67-3caf411935c1)

**Comment by mandliyarajendra11** [comment]
I would like to work on this issue under gssoc'23

**Comment by PiyushKalyanpy** [comment]
> I would like to work on this issue under gssoc'23

Sure I have assigned this task to you.

**Comment by rhithesh** [comment]
@PiyushKalyanpy  can i also wok on this issue

**Comment by PayalPadmalyaPrusty** [comment]
@PiyushKalyanpy I want to contribute.Please assign me

**Comment by ruchagosavi** [comment]
@PiyushKalyanpy  I would like to work on it please assign me!!
