### ISSUE TITLE
BUG:  No hover effect and wrong color scheme in the quick links section

### ISSUE THREAD

**Issue by NightFury742** [PiyushKalyanpy/GyanaGuru#213]
Links under the Quick links section  in the footer don't have hover effect and correct color scheme.

![IMG_20230529_165400](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119070798/b78e0ce2-f47c-4602-9321-d964b80b8e19)

**Comment by NightFury742** [comment]
I want to work on this issue, please assign it to me.

**Comment by lalitmee** [comment]
@NightFury742, is this happening in dark mode only or in both?

**Comment by NightFury742** [comment]
Happens only in dark mode

**Comment by lalitmee** [comment]
@NightFury742, ok then you can work on this. Assigning this to you.

**Comment by NightFury742** [comment]
Alright 👍
