### ISSUE TITLE
[Bug] Hovering Color Enhancement

### ISSUE THREAD

**Issue by vaibhav-xt** [PiyushKalyanpy/GyanaGuru#214]
### On hovering color becomes lighter and hence not visible.  
I am gssoc 2023 contributor. I would like to work on this issue. 

![Screenshot (479)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/90946899/df877baa-3145-4987-aa9b-9a6309ea4479)

**Comment by lalitmee** [comment]
@vaibhav-xt, ok. Assigning this to you.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
