### ISSUE TITLE
Adding instructions  to add firebase config details to `CONTRIBUTIONS GUIDE.md `

### ISSUE THREAD

**Issue by NightFury742** [PiyushKalyanpy/GyanaGuru#218]
When the cloned project is  initiated, it results in this **error.**
<br/>

![Screenshot from 2023-05-29 18-45-06](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119070798/59f037a3-4351-46b1-8330-3c2f3083fdff)

This happens because the **firebase config details** are empty in the **index.tsx**  file under the **firebase folder**.
<br/>

![Screenshot from 2023-05-29 18-44-42](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119070798/f44db714-f4af-4252-bf73-774216da9a84)

How to update these details when using the forked project can  be added to the ` CONTRIBUTORS GUIDE.md ` file so that contributors don't have a hard time finding a solution to this issue and running the project locally.

**Comment by NightFury742** [comment]
I am not assigned yet, can you please assign me this issue first

**Comment by PiyushKalyanpy** [comment]
Apologies for the inconvenience. I have now assigned the issue to you.

**Comment by ujjawaltyagii** [comment]
@NightFury742 hey ! could you please tell me quickly how to fix this ?

**Comment by ujjawaltyagii** [comment]
Already fixed it ! But thanks a ton for quick response 👍

**Comment by NightFury742** [comment]
> Already fixed it ! But thanks a ton for quick response +1

That's great,  It was my pleasure
