### ISSUE TITLE
[DOC]: Making the documents available in multiple languages. 

### ISSUE THREAD

**Issue by akash19coder** [PiyushKalyanpy/GyanaGuru#219]
### What feature?

We should make documents available in more languages especially in Hindi, Tamil, and Tamil. Doing it well will help contributors from various backgrounds understand Contributing Guide as well as the Code of Conduct which is the most important. Apart from that our project will also support inclusivity. 

### Agreement to Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
