### ISSUE TITLE
Adding a submit button

### ISSUE THREAD

**Issue by aadityamishraa** [PiyushKalyanpy/GyanaGuru#22]
There should be a submit button just below the email field for a better user experience.

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/37442807/ca8cdc53-2063-4103-9d78-db1ec6e79e0b)

**Comment by aadityamishraa** [comment]
I would like to implement this under GSSOC'23

**Comment by NehaShrama** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by aadityamishraa** [comment]
@PiyushKalyanpy bro I'm having issue with firebase API key

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/37442807/d3483ecf-9dd4-4b10-8ddd-f20b5865f4cf)

could you help me to solve that

**Comment by kirtiraj22** [comment]
Hey @aadityamishraa ,
You will have to generate your own api endpoints from firebase

**Comment by aadityamishraa** [comment]
ok, thanks
