### ISSUE TITLE
[Feat]: Send Email with Contact Form ✉️

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#220]
### What feature?

Remove FormSubmit.co and implement a new system for sending emails to improve reliability and streamline the email delivery process.

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shivaniyuvrajyadav** [comment]
hey @PiyushKalyanpy I would like to work on this issue. could you please assign it to me?

**Comment by akash19coder** [comment]
@PiyushKalyanpy Could you please elaborate a bit more on this issue?

**Comment by PiyushKalyanpy** [comment]
@shivaniyuvrajyadav How will you solve this issue ?? what are your plans ??

**Comment by shivaniyuvrajyadav** [comment]
@PiyushKalyanpy I was thinking of using emailjs to send emails through the contact form.

**Comment by PiyushKalyanpy** [comment]
Ok sure i am assigning this issue to you @shivaniyuvrajyadav

**Comment by ananyamanohar22** [comment]
if this issue is still open please assign it to me. I am a GSSOC'23 contributor
