### ISSUE TITLE
[Bug]: Home page font size too big 

### ISSUE THREAD

**Issue by dheeraj1129** [PiyushKalyanpy/GyanaGuru#225]
### What bug you encountered?

reduce the font size and image size also

### Show us the trouble with screenshots

![Screenshot (6)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/72201773/1c6d1124-84da-4fc0-9092-e70fc1cdec72)

### Which browsers are affected?

Brave

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by bhavyasingh75** [comment]
can you assign this issue to me?

**Comment by ansh-star** [comment]
I want to fix the font size of the website can u assign this issue to me

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
