### ISSUE TITLE
[Feat]: Update the Icons in dashboard page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#227]
### What feature?

Update the icons for the profile and help & Support tab, you have to use the icons from the Heroicons website and copy SVG code from the website and create a component in the file. 

website - https://heroicons.com/

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/280264ca-f465-42da-b88b-f97e39fc47be)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xabdulkhalid** [comment]
I can make the work done @PiyushKalyanpy, can you assign me for this issue ?


PS: I'm already assigned for an issue now i'm also opened a PR for that, remaining is your review only. Just merge and close it ASAP so that i can work on this issue.

**Comment by bhavyasingh75** [comment]
can you assign this issue to me?
