### ISSUE TITLE
add dark theme 

### ISSUE THREAD

**Issue by NehaSharma101** [PiyushKalyanpy/GyanaGuru#23]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by divyanshiet** [comment]
hey I would like to work on this issue. Kindly assign it to me

**Comment by PiyushKalyanpy** [comment]
Sure assigning this task.

**Comment by rahultomarr** [comment]
I'm here to contribute to the GSSOC'23.
Please assign me to do that.

**Comment by PayalPadmalyaPrusty** [comment]
@PiyushKalyanpy I want to work on this.Please assign me
