### ISSUE TITLE
[DOCS]:

### ISSUE THREAD

**Issue by Vikash0122** [PiyushKalyanpy/GyanaGuru#231]
### Description

The addition of the logo of the tech stacks used will make the readme.md file more attractive.

### Screenshots

Example:-
<img width="404" alt="ts" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/96245971/0def8976-fa60-4cc5-8711-ef55ce68145e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
We think that we should not add these logo , as we aldy have too many logos.
