### ISSUE TITLE
[Feat]: Add Settings Component to Setting Page ⚙️

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#233]
### What feature?

 The Settings page requires a new component to be added, following the design provided in the attached screenshot. The component should be created as a separate file in the component folder. Additionally, ensure that the buttons within the component are clickable and functional.
 
 ### 🎨 Tailwind colour classes 
- search placeholder: zinc-500
- search text colour: zinc-900
- search-border: zinc-200
- icon colour: zinc-900
- text colour ( unselected ): zinc-700
- background (unselected): white
- text colour (selected): zinc-900
- background(selected) : zinc-100

### Other Tailwind classes 
- border-radius: rounded-md
 
## ✨ Expected Deliverables:

- Create a new component for the Settings page based on the provided design.
- Place the component in the appropriate location within the component folder.
- Implement functionality for the buttons within the component to make them clickable.

## 🔀 Make sure to  use only Google material icons : 
- Find the desired icon on the Google Material Icons website (https://fonts.google.com/icons) and copy the class name associated with it.
- usage example -: `<span className="material-icons">arrow_outward</span>`

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/2c3887a8-b840-43bc-9614-696ba8a9e0cf)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishnu9865** [comment]
Thank you @PiyushKalyanpy for assigning it to me. 👍🏽😊🚀🚀🚀

**Comment by ujjawaltyagii** [comment]
If you need any help do let me know ! we can work on this issue in `collab`

**Comment by vishnu9865** [comment]
@ujjawaltyagii Thank you 😅. I would love to collaborate with you but I am almost done and only doing finishing touches. I hope to collaborate with in the future.
