### ISSUE TITLE
[Feat]: Create profile updating component for settings page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#234]
### What feature?

The Settings page requires a new component to be added, following the design provided in the attached screenshot. The component should be created as a separate file in the component folder. Additionally, ensure that the buttons within the component are clickable and functional.

 ### 🎨 Tailwind classes 
- delete button icon: rose-500
- button: zinc-900
- delete button border: zinc-200
- input label: zinc-500
- input border: zinc-200
- input text: zinc-900
- border-radius : rounded-md

✨ Expected Deliverables:

- Create a new component for the Settings page based on the provided design.
- Place the component in the appropriate location within the component folder.
- Implement functionality for the buttons within the component to make them clickable.
- Use react useState variable for input buttons.

🔀 Make sure to use only Google material icons :

- Find the desired icon on the Google Material Icons website (https://fonts.google.com/icons) and copy the class name associated with it.
- usage example -: `<span className="material-icons">arrow_outward</span>`

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/05f5eb1e-52c3-4b86-97fd-c602727ba1d7)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhi03ruchi** [comment]
Plz assign this task to me under gssoc'23.

**Comment by PiyushKalyanpy** [comment]
Sure @abhi03ruchi, I am assigning this task. Make sure to follow the given guidelines and tailwind classes.

**Comment by abhi03ruchi** [comment]
I am getting this error , when after i ran npm run dev.
<img width="1039" alt="Screenshot 2023-06-05 at 1 46 45 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/105661636/b433fb7c-15c7-4fa4-9afc-e1b659255a22">

Plz help

**Comment by PiyushKalyanpy** [comment]
This issue is resolved ?? If not please go through the contribution guide.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
