### ISSUE TITLE
Designing the ui for mobile and tablets [GSSoC'23]

### ISSUE THREAD

**Issue by adityatyagi-av** [PiyushKalyanpy/GyanaGuru#237]
### What feature?

I want to design the ui for mobile and tablet i.e make the entire website responsive so that it can be easily accessed in mobile devices
Please assign this issue to me under GSSoC'23

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Visbhavesh** [comment]
Please assign me this task under GSSOC 23

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
