### ISSUE TITLE
Add SCROLL-TO-TOP Button

### ISSUE THREAD

**Issue by krspriya** [PiyushKalyanpy/GyanaGuru#238]
### What feature?

I want to add a scroll to top button.
i want this task to be assigned to me.

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Visbhavesh** [comment]
Please assign me this task under GSSOC 23

**Comment by adarsh-aur** [comment]
I can easily complete this.
Please assign me this task under GSSOC 23

**Comment by lalitmee** [comment]
@PiyushKalyanpy, this is duplicate, I think we can close this.
