### ISSUE TITLE
[Feat]: adding hover effect in footer links

### ISSUE THREAD

**Issue by Iamdivyak** [PiyushKalyanpy/GyanaGuru#239]
### What feature?

when we hover over the footer links, the link should become darker. so that users can understand that this is clickable.

please sign it to me under gssoc'23 contributor

### Show us the magic with screenshots

nothing happens for now
<img width="953" alt="image" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/102896170/9f46e9dd-0587-4298-8d79-7404bc9b4709">

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Visbhavesh** [comment]
Please assign me this task under GSSOC 23
