### ISSUE TITLE
[DOCS]: Adding GSSoC contributor guide

### ISSUE THREAD

**Issue by ujjawaltyagii** [PiyushKalyanpy/GyanaGuru#243]
### Description

As GyanaGuru is a GSSoC project but the `project readme` doesn't mention anything about it so I would like to make few change in
project readme :

1. Adding GSSoC banner and a little info that this project is under gssoc
2. As contributors are just opening issues so adding short and rules for GSSoC contributors like : Dublicate Issues, opening PR only when issue is assigned, Labels and level marking, no multiple PRs until first one is merges
3. Test and merge conflict guidelines

- I want to work on this issue so assign this issue to me 
- Please add required GSSoC labels

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ujjawaltyagii** [comment]
@PiyushKalyanpy what do you think about this issue ?

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
