### ISSUE TITLE
[Feat]: Adding better images!

### ISSUE THREAD

**Issue by Shr-reny** [PiyushKalyanpy/GyanaGuru#245]
### What feature?

We can add better informative images.

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Please show us the samples of images

**Comment by Shr-reny** [comment]
These are a few samples:
![images](https://github.com/PiyushKalyanpy/GyanaGuru/assets/125943681/d4a7be4f-a16b-4937-b24f-e6e1d971ad41)
![download](https://github.com/PiyushKalyanpy/GyanaGuru/assets/125943681/5eec4cd6-2dd2-4532-a77c-982c2689e238)
![images (1)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/125943681/c995b6f4-a3e4-44b8-9245-bb337011c0bc)

**Comment by PiyushKalyanpy** [comment]
Ok, @Shr-reny thank you for your suggestion and interest in our project, Our theme follows images with 3d elements so, for now, we have not planned to change the current images from the home page.
