### ISSUE TITLE
[Bug]: On clicking logo - redirect to landing page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#247]
### What bug you encountered?

On the Dashboard page, inside the HomeSidebar component, when we click on the Logo component it should redirect to the landing home page. You can do this using `useRouter` in react.

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/a102b6dd-95a8-4472-a5a6-42cb320a9292)

### Which browsers are affected?

Other

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by itsPriyanshuhere** [comment]
Can I be assigned if this issue is still there under GSSOC'23?

**Comment by PiyushKalyanpy** [comment]
ok, @itsPriyanshuhere you can work on this issue.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
