### ISSUE TITLE
[Bug]: On clicking course - redirect to courses page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#248]
### What bug you encountered?

Inside landing home page, in Nav bar, when we click on Course it should redirect to `/courses`. You can use `useRouter` from react to redirect form one to another page.

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/55fe0789-3a5a-49b2-8a05-bcfc4e9785d1)

### Which browsers are affected?

Other

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by jibola2588** [comment]
Please assign this to me under GSSOC'23

**Comment by abhi03ruchi** [comment]
I would resolve this issue. Plz assign this task to me. I am well versed in frontend techs.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
