### ISSUE TITLE
Improve the navigation links in navbar

### ISSUE THREAD

**Issue by kirtiraj22** [PiyushKalyanpy/GyanaGuru#25]
I would like to improve the navbar links by adding a hover on it.

The current state:

- Navbar links have an underline on hover, which can appear outdated and detract from the overall design.
- The hover effect lacks a smooth transition, which can make the user experience feel less refined.

Proposed improvements:.
- I will add a smooth transition which will improve the user experience

can you assign me this task under GSSOC'23?

**Comment by PiyushKalyanpy** [comment]
Sure i have assigned this task to you.
