### ISSUE TITLE
[Bug]: the "Our Services" link in the footer is not functioning as expected and not directing users to the services page

### ISSUE THREAD

**Issue by ShubhaSwarup** [PiyushKalyanpy/GyanaGuru#250]
### What bug you encountered?

"Our Services" link has an href attribute specifying the correct URL. The href attribute should point to the services page. 
If the href attribute is missing or contains an incorrect URL or file name, it will prevent the link from working.

### Show us the trouble with screenshots

The "Our Services" link in the footer is not functioning
<img width="1395" alt="Screenshot 2023-05-31 at 12 59 52 PM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/112583158/658cb3d2-c310-40bd-81e7-ecc237ae79af">
<img width="814" alt="Screenshot 2023-05-31 at 1 01 49 PM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/112583158/da9b3bd4-ad81-48ef-8f44-ac87a1b9fd0d">

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by ShubhaSwarup** [comment]
Please assign me . I will fix this.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
