### ISSUE TITLE
[Bug]: Benefits in footer - redirecting to home page

### ISSUE THREAD

**Issue by vishwabandita** [PiyushKalyanpy/GyanaGuru#255]
### What bug you encountered?

When clicking on "benefits" in the footer, href is not assigned link of benefits page. Therefore it is redirecting to home page.  You can assign href="/whychooseus". This will redirect it correctly.

### Show us the trouble with screenshots

<img width="816" alt="footer correction" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/86146138/871039e6-9989-4f99-bcce-83bd697425fe">

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by Visbhavesh** [comment]
Please assign me this task under GSSOC 23

**Comment by RutamBhagat** [comment]
can you assign it to me. Its an easy fix.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
