### ISSUE TITLE
[Bug]: Making links under "get all types of courses" clickable

### ISSUE THREAD

**Issue by Illaf** [PiyushKalyanpy/GyanaGuru#257]
### What bug you encountered?

the links under the section "get all types of courses " do not direct to the required page. Therefore adding the paths to respective links and making necessary pages for them

### Show us the trouble with screenshots

![2023-06-01 (4)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/114517448/eabbf68f-f37c-46c1-85f9-0eaa5baf710d)

### Which browsers are affected?

Chrome, Microsoft Edge

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Hello @Illaf , thank you for your suggestion. Yes this should be implemented in our project, but for now we do not have those pages so this will take the user to a blank screen which we do not want. So we will look on this issue later.
