### ISSUE TITLE
Add some more categories in types of course and improve buttons styles

### ISSUE THREAD

**Issue by Pratik2026** [PiyushKalyanpy/GyanaGuru#26]
I want to add some more categories to the type of courses and also like to make the buttons accessible and improve their styling making them more attractive.

Please assign me this issue as a  part of @GSSOC'23.
![gyanguru](https://github.com/PiyushKalyanpy/GyanaGuru/assets/128511266/ca800e12-07e0-4558-b882-223893b5c076)

**Comment by PiyushKalyanpy** [comment]
Sure i am assigning this task to you.
