### ISSUE TITLE
Additions in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [PiyushKalyanpy/GyanaGuru#263]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes, documentation, etc*

Please assign this issue to me under Gssoc'23 @PiyushKalyanpy

**Comment by PiyushKalyanpy** [comment]
We already have a documentation issue template, and for Style changes, we use a feature request template. if you have any other template ideas, please specify them.

**Comment by Anshika-Jain02** [comment]
@PiyushKalyanpy Yes sir, how about resource addition like if somebody wants to add their notes or their self taught courses and other materials to foster collaborative growth

**Comment by PiyushKalyanpy** [comment]
Ya, but how will you do that ??

**Comment by Anshika-Jain02** [comment]
@PiyushKalyanpy 

Demo File:-         
*I will customise it accordingly*
[Resource_Addition.txt](https://github.com/PiyushKalyanpy/GyanaGuru/files/11696754/Resource_Addition.txt.txt)

**Comment by PiyushKalyanpy** [comment]
That's amazing, but how will used add them, and where it will be stored??

**Comment by Anshika-Jain02** [comment]
It will be added inside  ".github/ISSUE_TEMPLATE" as a resource_addition.yml file and when you merge it to your original branch then, it will automatically be reflected when anyone clicks on "New Issue" to raise an issue.

**Comment by PiyushKalyanpy** [comment]
But it will store those resources (pdf, img ..) on GitHub ??

**Comment by Anshika-Jain02** [comment]
@PiyushKalyanpy Sir, it will depend upon the source where the contributor has saved those resources. If he has saved it on his github then it will be saved on your github too.

**Comment by Anshika-Jain02** [comment]
@PiyushKalyanpy We can provide the guidelines to the contributor about how they need to save the resources in the contributing guidelines file.

**Comment by lalitmee** [comment]
> @PiyushKalyanpy Yes sir, how about resource addition like if somebody wants to add their notes or their self taught courses and other materials to foster collaborative growth

@Anshika-Jain02, sorry but I am not able to get your point. What resources you are talking about?

**Comment by PiyushKalyanpy** [comment]
We will add the option of submitting resources on our website only.

**Comment by lalitmee** [comment]
> We will add the option of submitting resources on our website only.

@Anshika-Jain02, this seems right instead of doing it in the github.
