### ISSUE TITLE
[Feat]: PR Template in .yml format

### ISSUE THREAD

**Issue by ManasMadan** [PiyushKalyanpy/GyanaGuru#265]
### What feature?

Pull Request Template means when someone opens a Pull Request, they will have a template that they can edit making it easier for maintainers of the project to review PR and make sure that no PR is submitted without proper description.

Please assign this issue to me under GSSoC'23

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManasMadan** [comment]
@PiyushKalyanpy Please assign me this under GSSoC 23

**Comment by lalitmee** [comment]
@ManasMadan, did you check that we already have a PR template.

**Comment by ManasMadan** [comment]
@lalitmee it doesn't seems that you have a PR template in the .GitHub folder
