### ISSUE TITLE
[Bug]: correcting the grammar in one section

### ISSUE THREAD

**Issue by Illaf** [PiyushKalyanpy/GyanaGuru#267]
### What bug you encountered?

Wrong grammar creates a bad impact and impression on user .
 The right section says "We provides" which is wrong grammar .
Correcting the sentence and thereby fixing the website. I know its a minor change but is necessary to get fixed.

### Show us the trouble with screenshots

![2023-06-04](https://github.com/PiyushKalyanpy/GyanaGuru/assets/114517448/95118ec7-bb97-4fcd-b099-c57484cf0099)

### Which browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge, Brave

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by abhi03ruchi** [comment]
I would like to work on the issue, plz assign it to me.

**Comment by lalitmee** [comment]
@abhi03ruchi, assigned :+1: 

Please check all the pages for grammatical mistakes.

**Comment by Illaf** [comment]
> @abhi03ruchi, assigned 👍
> 
> Please check all the pages for grammatical mistakes.

Okay thanks
I will check all the pages for grammatical errors

**Comment by abhi03ruchi** [comment]
<img width="793" alt="Screenshot 2023-06-15 at 10 22 42 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/105661636/6b3e95e1-10f2-4e72-9372-1aad672aaf1b">


I followed the steps in guidelines and added the firebase config, but still I am getting the error :  
<img width="1045" alt="Screenshot 2023-06-15 at 10 26 42 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/105661636/f59667c5-dfd8-44a8-827e-66c2078437b3">


Plz help...

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
