### ISSUE TITLE
Adding dynamic transition effects in "Why choose us" section

### ISSUE THREAD

**Issue by Illaf** [PiyushKalyanpy/GyanaGuru#268]
### What feature?

Adding interesting dynamic effects to the website thereby creating enhanced user experience

### Show us the magic with screenshots

![2023-06-04 (1)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/114517448/a0f4e62d-45e7-45cc-b249-c9fd26a7ad63)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
What type of dynamic effects do you want to add, please specify.

**Comment by afreen061** [comment]
I would like to work on this . please assign me this

**Comment by Illaf** [comment]
> What type of dynamic effects do you want to add, please specify.

For the text columns-
By making opacity 0 initially and translating in y direction from bottom to top orderwise with a slight delay of milliseconds.
Fading left for the image after the text columns emerge
