### ISSUE TITLE
Mobile optimization of the website

### ISSUE THREAD

**Issue by Illaf** [PiyushKalyanpy/GyanaGuru#269]
### What feature?

The website is not available in mobile mode. Building mobile mode for the website.

### Show us the magic with screenshots

![2023-06-04 (2)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/114517448/cba77ae3-2106-462f-bdc7-3b70f2e3e176)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SatyamKumar2002** [comment]
I want to solve this issue kindly assign it to me.
