### ISSUE TITLE
[Feat]: Adding a custom scroll-bar

### ISSUE THREAD

**Issue by ujjawaltyagii** [PiyushKalyanpy/GyanaGuru#270]
### Show us the magic with screenshots

![img](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115401171/cfec4dc9-3dc5-440e-9656-fb2ed6aa96d2)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ujjawaltyagii** [comment]
@PiyushKalyanpy Please assign this to me under `gssoc` with required labels

**Comment by PiyushKalyanpy** [comment]
Ok @ujjawaltyagii i am assigning this task to you.
