### ISSUE TITLE
favicon logo is not visible [Bug]: 

### ISSUE THREAD

**Issue by mandliyarajendra11** [PiyushKalyanpy/GyanaGuru#274]
### What bug you encountered?

The website's favicon logo and the color of the tab are the same, especially when we are on another tab, it is not visible at all. Adding a background color there can be a solution

### Show us the trouble with screenshots

current tab - 
![Screenshot (111)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119125519/6034ab42-4bb0-4bc6-98f7-3b29e3f921d0)

when we are on different tab - 
![Screenshot (112)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119125519/1ea85f73-6226-47cf-a3db-a798b9f15f09)

### Which browsers are affected?

Chrome

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by mandliyarajendra11** [comment]
please assign me this issue

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
