### ISSUE TITLE
[Feat]: Scroll to UP

### ISSUE THREAD

**Issue by arin-paliwal** [PiyushKalyanpy/GyanaGuru#275]
### What feature?

# Issue Title
Add Scroll-to-Top Component for Homepage and Other Pages

## Description
As a user, I want to have a scroll-to-top icon/button on the homepage and other pages of our project. This will allow me to quickly navigate to the top of the page without having to manually scroll.

## Steps to Reproduce
1. Open the homepage or any other page of the project.
2. Scroll down the page.
3. Observe that there is no scroll-to-top functionality available.

## Expected Behavior
When the user scrolls down a certain distance on the page, a scroll-to-top icon/button should appear on the bottom right corner of the screen. Clicking on this icon/button should instantly take the user back to the top of the page.

## Additional Information
- The scroll-to-top icon/button should have a fixed position, so it remains visible even when the user scrolls.
- The icon/button should be styled appropriately to match the project's design.
- The scroll-to-top functionality should work consistently across all supported browsers and devices.

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krspriya** [comment]
i also want to work on same issue. please assign it to me.
@PiyushKalyanpy
