### ISSUE TITLE
[Feat]: ADD more resources

### ISSUE THREAD

**Issue by Abhinavcode13** [PiyushKalyanpy/GyanaGuru#279]
### What feature?

addition of more youtube resources for learning

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhinavcode13** [comment]
@PiyushKalyanpy please assign me this issue under gssoc 23

**Comment by PiyushKalyanpy** [comment]
Please explain more about this.

**Comment by Abhinavcode13** [comment]
I just want to add more resources in the json file

**Comment by Abhinavcode13** [comment]
@PiyushKalyanpy

**Comment by PiyushKalyanpy** [comment]
We will not store our data in json file, we will store out data in firebase. If your questions is something else, please make a new issue and clearly specify the issue.
