### ISSUE TITLE
[Feat]: improve UI

### ISSUE THREAD

**Issue by Yashoda2003** [PiyushKalyanpy/GyanaGuru#280]
### What feature?

 According to  the description of website and moto of website, current images in website don't fit for it. They need to be replaced.
 I would like to do it under GSSoC'23.

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Please show the samples of images.

**Comment by PiyushKalyanpy** [comment]
We have not planned to update the images for now.
