### ISSUE TITLE
[Feat]: 

### ISSUE THREAD

**Issue by akankshachanana1** [PiyushKalyanpy/GyanaGuru#282]
### What feature?

Currently there is no hover effect on buttons which makes the site less interactive.I want to work on this issue by adding the hover effect on buttons as well as each item in community (by changing color or raising it a little bit on hover)

https://github.com/PiyushKalyanpy/GyanaGuru/assets/127978268/4392374c-9e17-4f23-8353-92343f747551

### Show us the magic with screenshots

I want to add hover effect like it is added here :

https://github.com/PiyushKalyanpy/GyanaGuru/assets/127978268/7fcf91e1-f653-4bd2-92f7-a3935daaada5

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
