### ISSUE TITLE
[Bug]: Changing the colour of the text on hovering in "why choose us" section

### ISSUE THREAD

**Issue by Illaf** [PiyushKalyanpy/GyanaGuru#283]
### What bug you encountered?

On hovering in text columns, the colour of the divs change to light green which makes the visibility of the text  inside that div a bit difficult and barely visible. Hence changing the text colour to black(or any other colour you suggest) will make it easier for the user to read.

### Show us the trouble with screenshots

![2023-06-07](https://github.com/PiyushKalyanpy/GyanaGuru/assets/114517448/e781b1f0-01a6-4374-83e2-c9fb2722a470)

### Which browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge, Brave

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by NANDHINI45** [comment]
I am interested to work on this issue can you please assign me this issue under GSSOC'23 @PiyushKalyanpy
