### ISSUE TITLE
[Feat]:   Auto-select System Theme for Dark/light Mode

### ISSUE THREAD

**Issue by bhaskarkumar1** [PiyushKalyanpy/GyanaGuru#284]
### What feature?

I wanted to reach out and suggest an enhancement for the Dark Mode feature in your [app/website]. Currently, the user has the option to manually toggle between dark and light modes. However, I believe it would greatly enhance the user experience if the Dark Mode could automatically adjust based on the user's system preference, providing a seamless and personalized experience.

I noticed that many operating systems and browsers now support the "prefers-color-scheme" media query, which allows developers to detect the user's system-wide theme preference. By incorporating this functionality into your Dark Mode feature, your [app/website] can automatically detect and apply the user's preferred theme when they visit.

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NANDHINI45** [comment]
I am interested to work on this issue can you please assign me this issue under GSSOC'23 @PiyushKalyanpy

**Comment by PiyushKalyanpy** [comment]
@bhaskarkumar1 That is already implemented, please show us gif, if you think that there is a bug.

**Comment by PiyushKalyanpy** [comment]
-

**Comment by bhaskarkumar1** [comment]
yes i checked @PiyushKalyanpy  and its working correctly .
