### ISSUE TITLE
[Docs]: Add more checkbox in issue and PR templates

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#285]
### Description

Inside issue templates add the checkbox after the code of conduct checkbox for 
- I am GSSoC contributor
- I wan to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parasss19** [comment]
hii @PiyushKalyanpy  i wan to work on this issue please assign me
