### ISSUE TITLE
Improve Footer Section

### ISSUE THREAD

**Issue by parthpathakpp1** [PiyushKalyanpy/GyanaGuru#29]
The footer section needs an improvement and some quick links . I can make footer section look good.

**Comment by parthpathakpp1** [comment]
Assign this issue to me under ** @GSSOC'23**

**Comment by PiyushKalyanpy** [comment]
Assigning this task to you.

**Comment by parthpathakpp1** [comment]
> Assigning this task to you.

Getting this error while trying to run it locally in terminal
![gyanaguru error](https://github.com/PiyushKalyanpy/GyanaGuru/assets/85991449/a5338f64-3042-45ae-af1a-24fcfca090f5)
![errror2](https://github.com/PiyushKalyanpy/GyanaGuru/assets/85991449/ef08fad8-c9c9-4c58-af1a-34078c45e389)

**Comment by kasturimandlik** [comment]
@PiyushKalyanpy 
Hello, I would like to change the styling in the footer section.
I would like to align it properly and enhance the user experience
Please assign me this issue.
I would like to work on this issue under GSSOC'23.

**Comment by parthpathakpp1** [comment]
> @PiyushKalyanpy Hello, I would like to change the styling in the footer section. I would like to align it properly and enhance the user experience Please assign me this issue. I would like to work on this issue under GSSOC'23.

Currently I am working on this issue.

**Comment by parthpathakpp1** [comment]
> Assigning this task to you.

@PiyushKalyanpy  **This is the modified PR-:**
https://github.com/PiyushKalyanpy/GyanaGuru/pull/101
