### ISSUE TITLE
adding hover effect on images

### ISSUE THREAD

**Issue by gaur15** [PiyushKalyanpy/GyanaGuru#291]
### What feature?

adding hover on images enhance the looks of the website and enhance interaction

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Humaira-Sadia** [comment]
Hello @PiyushKalyanpy I believe I can create a beautiful and user interacting hover effect on images and cards, which will enhance the quality of the website...
I would be very happy to work on this project , can you please assign this issue to me :)

**Comment by PiyushKalyanpy** [comment]
What are the updates??

**Comment by gaur15** [comment]
> What are the updates??

I'm working on this issue just some few changes left

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
