### ISSUE TITLE
 [Feat]: Hovering effect on the footer of the page

### ISSUE THREAD

**Issue by smritimangal26** [PiyushKalyanpy/GyanaGuru#298]
### What feature?

Adding a hovering effect on the footer of the page which contains links to the socials, home, about us section etc, it will make it look more good and user friendly
Kindly assign me this issue under GSSOC'23

### Show us the magic with screenshots

![Screenshot (43)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/129358356/464dd04d-48ab-4fe9-ac37-06688b2ae253)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by smritimangal26** [comment]
This issue is not been resolved till now , It has been assigned since 2 weeks
Kindly assign this to me

**Comment by SatyamKumar2002** [comment]
I want solve this issue kindly assign it to me. I will take maximum 1 day in this to resolve

**Comment by smritimangal26** [comment]
I can work on this , please assign me

**Comment by smritimangal26** [comment]
Thanks for assigning, I will start working on it
