### ISSUE TITLE
Need to create new about us page

### ISSUE THREAD

**Issue by MohamedMafaz** [PiyushKalyanpy/GyanaGuru#299]
### What bug you encountered?

Hey! Our websites' home page looks visually appealing. But, the about us page doesn't match with the home page design. SO we need to create a new UI and need to develop it. I'm a UI/UX Designer & Front-End Developer. Kindly assign me this issue under GSSoC'23

### Show us the trouble with screenshots

![Screenshot (50)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/113255500/dc4e2427-579f-42fd-8a7a-a3ceda01b27d)

### Which browsers are affected?

Chrome

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Ok @MohamedMafaz  Please show the design screenshot of about us page, before your make a PR

**Comment by lakhan06** [comment]
> Ok @MohamedMafaz Please show the design screenshot of about us page, before your make a PR

i also want to work on the issue

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
