### ISSUE TITLE
Redesign Contact Us to Subscribe to Newsletter section in Landing Page  (index.js)

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#3]
The current Contact Us section in the Landing Page (index.js) needs a redesign to make it more visually appealing and user-friendly. The section should be eye-catching and encourage visitors to reach out to us.

Some suggestions for improvements include:

- Adding a form to make it easier for visitors to submit their information.
- Consider adding a headline or tagline to the section to convey the purpose or benefit of contacting us.
- Using contrasting colors to make the section stand out.
- Ensure the section is responsive and displays well on different screen sizes.
- Use whitespace effectively to make the section more visually appealing and easy to read.

Contributors are welcome to submit their design proposals and collaborate with the team to implement the changes. Please feel free to leave comments and suggestions on this issue.

Let's make the Contact Us section of our Landing Page more engaging and effective! 🚀

**Comment by PiyushKalyanpy** [comment]
> Hi I would like to work on this issue

Thank you for expressing your interest in working on this issue! We appreciate your enthusiasm and willingness to contribute. I have assigned this task to you.

**Comment by AmanMittal-3305** [comment]
Thanks for assigning

**Comment by PayalPadmalyaPrusty** [comment]
@PiyushKalyanpy  I want to contribute.Please assign me
