### ISSUE TITLE
[Feat]: Need to create the FAQs section

### ISSUE THREAD

**Issue by kharshita590** [PiyushKalyanpy/GyanaGuru#301]
### What feature?

i want to make the faq section working 

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by smty2018** [comment]
@PiyushKalyanpy can you please assign me this issue.it has been 2 weeks

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
