### ISSUE TITLE
[Feat]: Enhacement of UI by adding animations

### ISSUE THREAD

**Issue by anamika7153** [PiyushKalyanpy/GyanaGuru#303]
### What feature?

I'm in GSSoC'23.

I would like to make the UI more attractive yet decent by adding some animations.

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Please specify where you want to add animations ( on which pages and which element ) also please tell which library will you use for the animations.

**Comment by anamika7153** [comment]
> Please specify where you want to add animations ( on which pages and which element ) also please tell which library will you use for the animations.

@PiyushKalyanpy  I'm thinking of achieving something like this. For this, I'll use AOS Library.


https://github.com/PiyushKalyanpy/GyanaGuru/assets/66116440/abfda82f-9361-499c-9ec7-c0b6f244d8fe

**Comment by PiyushKalyanpy** [comment]
Can you do it using framer motion library

**Comment by anamika7153** [comment]
> 

sure :)

**Comment by anamika7153** [comment]
> Can you do it using framer motion library

sure :)

**Comment by PiyushKalyanpy** [comment]
Ok I have assigned you the issue and please create different issues for different pages (animations) also do not create a pr before showing us the preview here in the issue.

**Comment by anamika7153** [comment]
> Ok I have assigned you the issue and please create different PR's for different pages (animations) also do not create a pr before showing us the preview here in the issue.

I didn't quite understand "create different PR's for different pages (animations)"

**Comment by PiyushKalyanpy** [comment]
Ok means if you are adding animaton in landing page the create a pr whose title will be like : (adding animation in landing page) , do not push too many animation code changes in a single pr. 
for landing page animation - create 1 pr and for dashboard page animation create another pr.

**Comment by anamika7153** [comment]
> Ok means if you are adding animaton in landing page the create a pr whose title will be like : (adding animation in landing page) , do not push too many animation code changes in a single pr. for landing page animation - create 1 pr and for dashboard page animation create another pr.

ok got it and I'll provide preview before creating PR :)

**Comment by anamika7153** [comment]
@PiyushKalyanpy  I also wanted to ask when can we start creating issues. Is the work still in progress?

**Comment by PiyushKalyanpy** [comment]
Please let me know which component you will start with.

**Comment by anamika7153** [comment]
> Please let me know which component you will start with.

home page

**Comment by anamika7153** [comment]
> @PiyushKalyanpy I also wanted to ask when can we start creating issues. Is the work still in progress?

@PiyushKalyanpy  ??

**Comment by PiyushKalyanpy** [comment]
ok you can work on that and share the preview have once coded then you can create the pr.
