### ISSUE TITLE
[Feat]: "Contact Us" Section's Alignment Improvement

### ISSUE THREAD

**Issue by iamRabia-N** [PiyushKalyanpy/GyanaGuru#304]
### What feature?

The website design is really nice but it can be improved by making the "Contact Us" section's correct alignment from left-aligned to center-aligned. This will add more value to the overall design of website.

### Show us the magic with screenshots

**Current Alignment**
![GyanaGuru (2)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115794049/d6599fe6-7630-4718-b639-ea4269041972)

**Expected Updated Alignment**
![GyanaGuru (1)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115794049/37af2818-6e31-4982-9c5a-5cd8164337f5)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
@iamRabia-N This design is not aligned with the project design.
