### ISSUE TITLE
About us section back button in dark mode 

### ISSUE THREAD

**Issue by saurabh29r** [PiyushKalyanpy/GyanaGuru#308]
### What bug you encountered?

In Dark mode , when we click on about page the  visibility of back icon is not good. the background color need to change.
Assign me this issue, I will change it.

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/48233777/ca61430c-20ce-4010-a2d1-c885c7c95c6f)

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Please update the title and remove GSSOC .
