### ISSUE TITLE
Adding the FAQ page

### ISSUE THREAD

**Issue by Ankita3503** [PiyushKalyanpy/GyanaGuru#312]
### What feature?

Hi ,
I want to add the FAQ page . As it says 404 not found , so I want to add the FAQ page.

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/94631478/beb27989-0d36-4d6a-ac36-756ee449bfb8)
Like this kind of idea I want to implement in FAQ page.

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Hey @yash8917 , please create a new Issue I will assign you there.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.

**Comment by Ankita3503** [comment]
Sorry for the delay as I have my university paper so I delayed it . But I
want to contribute I have done half of the project .
Please assign me

**Comment by Ankita3503** [comment]
Thank you so much

**Comment by PiyushKalyanpy** [comment]
We will be uploading new design with issue in 2-3 days.

**Comment by Ankita3503** [comment]
Okay, thank you!
