### ISSUE TITLE
[Feat]: Hover Effect on "contact us " section

### ISSUE THREAD

**Issue by smritimangal26** [PiyushKalyanpy/GyanaGuru#317]
### What feature?

A hover effect can be added to the contact us section which will make it look more attractive
Kindly assign me this issue under GSSOC'23

### Show us the magic with screenshots

![Screenshot (44)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/129358356/7c07f743-f485-485d-a630-9442695fdb95)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by smritimangal26** [comment]
I am working on the issue, there was some problem in PR

**Comment by PiyushKalyanpy** [comment]
Sorry for the inconvenience, by mistake I have closed this issue.

**Comment by smritimangal26** [comment]
Thankyou I will raise the PR within 1 day
