### ISSUE TITLE
[Feat]: Want to add Color themes in the website

### ISSUE THREAD

**Issue by lakhan06** [PiyushKalyanpy/GyanaGuru#319]
### What feature?

- I want that their should be a option so that user can select color theme of the website according to his/her choice and get a better user experience .
- I will add a themes option on the right side of each page and will change the color according to user choice by using JavaScript.
- I will uses root elements to change the color according to user choice.
- I will also stored the data of color theme in user local storage that user choose and when user again come on website then he will see the color theme according to his/her choice.

### Show us the magic with screenshots

Below is the example of color themes and more can be added
Color theme1:
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119161467/f1aed1b2-a7c8-4cfb-be1c-2628fc3f8baa)

Color Theme 2:

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119161467/430a15aa-a091-4453-afbe-a37b64c9fa8e)

Color Theme 3:
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/119161467/dc54600b-5a7c-4fda-be28-3604cf1296b7)

and more can be added according to what better look for website .

 

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
@lakhan06 Thankyou for your suggestion, but we would not like to add the color themes in our website.
