### ISSUE TITLE
Link of header section not working

### ISSUE THREAD

**Issue by sumitkr2000** [PiyushKalyanpy/GyanaGuru#32]
Hey @PiyushKalyanpy The links of the header section of your website are not wiring. Please assign me this issue so I can fix it. Thank you!

**Comment by rhithesh** [comment]
@PiyushKalyanpy even I would like to work on this

**Comment by sumitkr2000** [comment]
@rhithesh I am working on this issue. Please raise another if you want to contribute. Thank you!

**Comment by ayon037** [comment]
I want to contribute on this issue. Please assign me this issue under GSSOC'23.
