### ISSUE TITLE
[Bug]: The signup page is broken

### ISSUE THREAD

**Issue by maitri-vv** [PiyushKalyanpy/GyanaGuru#321]
### What bug you encountered?

The UI for signup page is broken 

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/87691594/756f8a97-18a4-436f-89ba-73fd5d1ef09c)

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by PiyushKalyanpy** [comment]
We already have a PR for this issue.
