### ISSUE TITLE
[Bug]: Login button clicking does not redirect to dashboard page

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#323]
## 🐞 Issue: Clicking does not redirect to dashboard page

- When clicking on login button in login page, the expected behavior of redirecting to the dashboard page is not occurring.
- Possible solution:
  - Utilize appropriate cookies and middleware to handle authentication and sessions.
  - Use auth context from the context folder to verify if the user is logged in.

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/7e88c53c-a623-4ef7-be3a-2a7add4d0fe3)

### Which browsers are affected?

Firefox, Chrome, Safari, Microsoft Edge, Brave, Other

### Agreement to Code of Conduct

- [X] Code of Conduct

**Comment by ayushpandey101** [comment]
kindly assign this issue to me under gssoc23

**Comment by Humaira-Sadia** [comment]
Hii @PiyushKalyanpy I think I can resolve this issue, if this is not yet resolved please assign this to me :)

**Comment by ayushpandey101** [comment]
@PiyushKalyanpy when I am replicating the issue it is working perfectly, the user is getting redirected after login 

https://github.com/PiyushKalyanpy/GyanaGuru/assets/127859041/eb8630cc-1177-4508-9ff8-b30ec8a9e120
