### ISSUE TITLE
[Feat]: Adding ARIA to provide additional information to assistive technologies

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#324]
### What feature?

🔖 **Issue Description:**
Enhance website accessibility by adding Aria attributes. Aria attributes play a crucial role in providing additional information to assistive technologies, ensuring a better user experience for individuals with disabilities.

💡 **Key Points:**
- Implement Aria attributes to important elements throughout the website.
- Use descriptive labels that accurately convey the purpose or function of each element.
- Focus on interactive elements like buttons, links, and form fields.
- Verify compatibility and effectiveness by testing with various screen readers and assistive technologies.

🌟 **Contribution Opportunities:**
- Identify elements requiring Aria attributes and suggest appropriate implementations.
- Provide feedback on Aria attribute usage and propose improvements.
- Test website accessibility using different screen readers and assistive technologies, reporting any issues or recommendations.

🌐 **Useful Resources:**
- [MDN Aria Guide](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)

Feel free to comment, ask questions, or contribute to this issue. Your active participation is highly appreciated!

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vishnu9865** [comment]
@PiyushKalyanpy Sir, I would like to solve this Issue. Please do assign it to me under GSSoC'23.
Thank you in advance. 🚀🚀👍🏽😊
Regards,
@vishnu9865

**Comment by vishnu9865** [comment]
- Regarding this Issue, I'm mostly adding `role` and `aria-description` to important and isolated components with extra attributes like `aria-placeholder`, etc for Form controls.
 - Most accessibility guides emphasize on adding a11y attributes mostly for non-text elements.

Is this okay with you ?
