### ISSUE TITLE
[Feat]: Replication UI design for video player screen

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#326]
### What feature?

Some of the components of the video player screen have been already coded, However, we need assistance from the community to complete the remaining part.

## Task

- Replicate the remaining UI components based on the provided design
- Ensure responsiveness and compatibility across different devices
- Follow the existing coding standards and project structure

## Guidelines

- Familiarize yourself with the existing codebase and design guidelines
- Maintain consistency with the existing UI elements and styles
- Use appropriate naming conventions for classes, functions and components 
- Ensure clean and organized code
- Test thoroughly to identify and fix any bugs or issues
- Make sure that you create different pull requests for different features and do not push unnecessary files, like  `package.json` or `package.lock.json`

Feel free to claim the issue and start working on it. If you have any questions or need clarification, please leave a comment on the issue thread.

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/21560814-255b-45f1-b193-5a6da90ec0e8)

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vidip-Ghosh** [comment]
Can I work on this issue?

**Comment by PiyushKalyanpy** [comment]
Yes, @Vidip-Ghosh , please start making notes card on right-hand side , use Tailwind CSS and make separate components inside the same file for time and tags.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue, as it has been inactive for a long time. If you think you want to work on this issue please create a new ISSUE.
