### ISSUE TITLE
[Feat]: Vanilla Tilt in WHY CHOOSE US

### ISSUE THREAD

**Issue by bhavyanarnoli** [PiyushKalyanpy/GyanaGuru#329]
### What feature?

I can make the Free Education column and the two other have a vanilla tilt ( for better interactivity). im adding a video of how it looks when it's done because it's essentially the same square which tilts with the pointer

### Show us the magic with screenshots

https://www.google.com/search?q=vanilla+tilt&source=lmns&tbm=vid&hl=en&sa=X&ved=2ahUKEwj9ja-cwsn_AhXQqdgFHV7MBnYQ_AUoAnoECAEQAg#fpstate=ive&vld=cid:61c895eb,vid:weMGDrV86Fc please see the last 5 secs of the video ans assign it to me under GSSOC 

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Okay i am assigning this task. But please make sure to use tailwind where  it can be used.
