### ISSUE TITLE
[Feat]: Adding underline under each heading of every section and hover effect on the heading

### ISSUE THREAD

**Issue by smritimangal26** [PiyushKalyanpy/GyanaGuru#332]
### What feature?

Adding hover effect and underline using HR tag will make the heading look more effective 
kindly assign me under GSSOC'23

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/129358356/789a17e3-2f38-4325-b16c-7631ef280d73)
 
like under the heading Our Services , why choose us , contact us 

### Agreement to Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PiyushKalyanpy** [comment]
Hey @smritimangal26 , thank you for your suggestion and interest but currently, we are not accepting the issue for the Landing page. Please find an issue in the dashboard or course pages. 
dashboard  : [Click here 🔗](https://gyanaguru.vercel.app/dashboard)

**Comment by smritimangal26** [comment]
okay
