### ISSUE TITLE
[Docs]:

### ISSUE THREAD

**Issue by bhavyanarnoli** [PiyushKalyanpy/GyanaGuru#335]
### Description

How to do in firezilla ang generate api key to run on local server , it might not be easy for someone new can add it in readme,d

### Screenshots

To obtain the details required for the Firebase configuration variables (NEXT_PUBLIC_FIREBASE_API_KEY, NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN, etc.), you'll need to follow these steps:

Go to the Firebase console at https://console.firebase.google.com/ and sign in with your Google account.
Create a new Firebase project or select an existing project.
Once inside the project, click on the "Settings" icon (gear icon) next to "Project Overview" on the left-hand side.
In the project settings, navigate to the "General" tab.
Scroll down to the section titled "Your apps" and click on the "</>" icon to add a new web app to your project.
Register the web app by providing an app nickname (e.g., "My Next.js App") and click on the "Register app" button.
Firebase will generate the configuration details for your app, including the API key, auth domain, project ID, storage bucket, messaging sender ID, and app ID.
Copy the corresponding values for each configuration detail and use them in your Next.js project as environment variables (NEXT_PUBLIC_FIREBASE_API_KEY, NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN, etc.) or directly in your Firebase configuration code.
By following these steps, you will be able to access the required details for your Firebase project and configure them in your Next.js application.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bhavyanarnoli** [comment]
ill add commands to it give under gssoc label

**Comment by lalitmee** [comment]
@PiyushKalyanpy, I think @bhavyanarnoli is talking about the steps which you and I were discussing to setup in our documentation.

I haven't checked our all the documentations but I am not sure if its already there or not.

**Comment by PiyushKalyanpy** [comment]
Hey @bhavyanarnoli ye already have guides for adding firebase config in the local server.
