### ISSUE TITLE
Want to add a new Attractive UI Game i.e Car Racing game

### ISSUE THREAD

**Issue by yash8917** [PiyushKalyanpy/GyanaGuru#339]
I have made a new game which is user friendly and interactive car racing game now i want to add this game in your repo. please assign this it to me under the GSSOC '2023

**Comment by PiyushKalyanpy** [comment]
What type of game and how it will be helpful in this project, please explain.

**Comment by yash8917** [comment]
Its a car racing game user will play with help of arrow keys and achieve the score according to that.
![Screenshot 2023-06-18 193139](https://github.com/PiyushKalyanpy/GyanaGuru/assets/90241440/bf3b134e-6711-4f8d-aa1f-67588945c556)

**Comment by PiyushKalyanpy** [comment]
But how it will be helpful to a learning platform Gyanaguru??

**Comment by yash8917** [comment]
NO its not helpful in your repo

**Comment by PiyushKalyanpy** [comment]
Then ?

**Comment by yash8917** [comment]
Sir Why You open ?

**Comment by PiyushKalyanpy** [comment]
You have closed it as `completed`, you have to close it as `not planned`
