### ISSUE TITLE
[Bug]: Run Error,Nextjs.config, firebase Api

### ISSUE THREAD

**Issue by Pratik-11** [PiyushKalyanpy/GyanaGuru#345]
### What bug you encountered?

When i am trying to run the project i am encountering these errors, I t might be some bugs or some problems on my system maybe .

I think there is some error in some recent merge maybe it can be checked.

### Show us the trouble with screenshots

![localhost_3000 - Brave 6_19_2023 11_09_01 AM](https://github.com/PiyushKalyanpy/GyanaGuru/assets/72139212/41811a78-cece-4fd5-8398-935a962b9052)

![next config js - GyanaGuru - Visual Studio Code 6_19_2023 11_13_58 AM](https://github.com/PiyushKalyanpy/GyanaGuru/assets/72139212/10168d65-774c-4d00-9589-1f736b356994)

### Which browsers are affected?

Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Read the contribution guide, please.
