### ISSUE TITLE
Add FAQ Page Content

### ISSUE THREAD

**Issue by prashanth772** [PiyushKalyanpy/GyanaGuru#348]
### What feature?

I wanted to update FAQ section page 

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/124067333/5491aa41-8631-4be5-a617-abb76d04e1ab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by mohitparmar1** [comment]
i want to work on this issue!

**Comment by Nishitbaria** [comment]
Hey **@mohitparmar1**  Contact Project Admin via Discord
