### ISSUE TITLE
[Feat]: Add "Programming Languages" Option in Category Section

### ISSUE THREAD

**Issue by NarendraKoya999** [PiyushKalyanpy/GyanaGuru#350]
### Issue Description:
- Add **` Programming Languages`** Option in **` Category Section.`**

### For Reviewers:
- **`Generally, In Trends, Ask Strong Foundation for Any Specialized Language in Any Tech and Non-Tech Job Interviews.`**
- **`So, Commanding on Particular Language to Candidate. Must Learn One Specific Programming Language.`**
- Finally, I would like to **`Suggest Add this Feature for Future Scope.`**

### Where to Put It (Screenshot Explains)
![gyanaguru-1](https://github.com/PiyushKalyanpy/GyanaGuru/assets/84512164/c59f1776-4caf-4b4c-93ee-478279e5f230)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
This can only be done by the admin from admin pannel.
