### ISSUE TITLE
[Feat]: Add 'Edit' ,'Save', 'Cancel' Options on Right Side of User Dashboard for Profile Editing

### ISSUE THREAD

**Issue by NarendraKoya999** [PiyushKalyanpy/GyanaGuru#351]
### Issue Description
- Add **`Edit , Save, Cancel`** Options on Right Side of **`Dashboard for Profile`** Editing.
- This Feature is only **`Editable Option for User Name, User Photo and Current Position`** Options.

### For Reviewers:
- Who wants to **` Edit , Save & Cancel`** Small Details like **` User Photo, User Name and Current Position `** of User simply Instead of **` Going to Settings and Edit and Save & Cancel for all Details.`**
- **` Another, Going to Editing the Details. After Editing is Completed, User wants to Either Click on Save OR Cancel Buttons.`**

### Screenshot of My Feature
![gyanaguru-2](https://github.com/PiyushKalyanpy/GyanaGuru/assets/84512164/a82c0b74-0da3-4078-8d7e-8ab25744daa3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [x] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Thank you for your suggestion, @NarendraKoya999 . However, we have already modified the design and will make it public within the next 3-4 days.
