### ISSUE TITLE
[Feat]: Better Ui of the About Page

### ISSUE THREAD

**Issue by Tisha6661** [PiyushKalyanpy/GyanaGuru#358]
### What feature?

Add better list formats, padding, heading and better design to the About Us page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Can you show us a screenshot or design?

**Comment by Tisha6661** [comment]
Yes, to make it a bit arranges and classy-
Right row there is no design-
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/98682478/b0b61482-a44e-460a-8020-87c711593033)

something like this, it's just the basic idea-
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/98682478/cc2da3b1-7e54-4e1b-81c6-3c5ab491fdf2)

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/98682478/d0443df9-0b84-4291-8d21-6bf9b49e7c81)

**Comment by PiyushKalyanpy** [comment]
What are the updates, please let us know.

**Comment by Tisha6661** [comment]
@PiyushKalyanpy Actually I am working with firebase for the first time, so I didn't get it at first, but now I understood it, I will create a PR upto tomorrow.

**Comment by PiyushKalyanpy** [comment]
Ok sure.

**Comment by Tisha6661** [comment]
@PiyushKalyanpy  I have created a pull request regarding this task, please verify and merge it.
