### ISSUE TITLE
[Feat]: Creating a up arrow button with hover effect [GSSoC'23]

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [PiyushKalyanpy/GyanaGuru#361]
### What feature?

- Create a component of up arrow button 
- This button will invoke on scrolling downward to the webpage
- On pressing this button, user will directly move to the head of the webpage
- Adding hover effect to give a nice look
- Adding a pulse effect around the arrow button to attract the users

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Avdhesh-Varshney** [comment]
@PiyushKalyanpy please assign this task to work on it and give a valuable contribution under GSSoC'23 program

**Comment by PiyushKalyanpy** [comment]
Can you please show us a demo ??

**Comment by Avdhesh-Varshney** [comment]
@PiyushKalyanpy 

https://github.com/PiyushKalyanpy/GyanaGuru/assets/114330097/86e89a6b-f718-4d4a-8087-98b1be4a4368

Please /assign it to me

**Comment by PiyushKalyanpy** [comment]
What are the updates?

**Comment by Avdhesh-Varshney** [comment]
> What are the updates?

Sorry, I don't know tailwind css. 

<br>

So, I cannot create this arrow in tailwind css. I can create this using CSS, SASS, SCSS, and even in reactjs. From that day, I am learning Tailwind CSS. But this takes a lot of time. So, if you can assign this task except tailwind css then i will create pr within 24 hours.

Thanks for your patience.

**Comment by PiyushKalyanpy** [comment]
Hey @Avdhesh-Varshney thank you for your interest in our project, but we cannot allow the contribution without tailwind css.
