### ISSUE TITLE
youtube.tsx  is written in class based components, needs to be function based.

### ISSUE THREAD

**Issue by rhithesh** [PiyushKalyanpy/GyanaGuru#37]
I would like to work on this issue.

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23.
Please assign it to me. Thank you.

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GirlScript-Summer-of-Code'23
Please assign it to me. Thank you.

**Comment by Sathvik902** [comment]
I would like to contribute to this issue as a part of @GSSOC'23
Please assign it to me. Thank you.

**Comment by Sathvik902** [comment]
Thank You!
