### ISSUE TITLE
[Feat]: About us page need UI improvement

### ISSUE THREAD

**Issue by HimanshuNarware** [PiyushKalyanpy/GyanaGuru#386]
### What feature?

The UI of the About us page is very simple, and not match with UI of the website, I want to work on this issue.

### Show us the magic with screenshots

![54](https://github.com/PiyushKalyanpy/GyanaGuru/assets/83147410/51e78458-f05d-4c15-957f-7ad28d204ae6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We will add new design for about us page in next 2-3 days.
