### ISSUE TITLE
[Feat]: Toggle button is not working in the sign up page

### ISSUE THREAD

**Issue by HimanshuNarware** [PiyushKalyanpy/GyanaGuru#387]
### What feature?

The Toggle button is not present in the sign up page ,I want to work on this issue.

### Show us the magic with screenshots

Signup page
![53](https://github.com/PiyushKalyanpy/GyanaGuru/assets/83147410/3444bf69-b0f9-4106-80e8-03be8d572d66)

Normal page
![52](https://github.com/PiyushKalyanpy/GyanaGuru/assets/83147410/8b24192e-ed52-4995-89a6-7ebc196aea57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
we have already updated the new design for auth pages.
