### ISSUE TITLE
[Bug]: make it black

### ISSUE THREAD

**Issue by bhavyanarnoli** [PiyushKalyanpy/GyanaGuru#390]
### What bug you encountered?

<img width="313" alt="image" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/108413315/3fad8339-0cb6-4b95-a621-c43ede5c2864">

### Show us the trouble with screenshots

white is not visible in blue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by bhavyanarnoli** [comment]
ill make it black

**Comment by akanksha984** [comment]
Please assign it to me under gssoc'23. I want to work on it

**Comment by PiyushKalyanpy** [comment]
we will add new issues with new designs in next 2-3 days
