### ISSUE TITLE
[Feat]: Scroll to Top button

### ISSUE THREAD

**Issue by pavitrachavda97** [PiyushKalyanpy/GyanaGuru#392]
### What feature?

Scroll to top button allows users to quickly navigate to the top of a page with a single click or tap. It offers a convenient way to return to the beginning of a long webpage without manually scrolling.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by komalioruganti** [comment]
Can I work on this issue? Can you assign me this? I have made a similar feature for multiple projects until today. I would love to contribute to your project. 
Thank you in advance

**Comment by PiyushKalyanpy** [comment]
what are the updates @pavitrachavda97 ?

**Comment by pavitrachavda97** [comment]
Hi @PiyushKalyanpy 
I wanted to inform you that I have completed the issue as per the requirements. Although the issue has been closed, I apologize for the delay in creating the pull request. I will proceed with creating the pull request immediately to ensure the changes are reviewed and merged.

Thank you for your understanding, and I appreciate your patience.
