### ISSUE TITLE
[Feat]: Add contact us page to a google map 

### ISSUE THREAD

**Issue by Pallavi-star2002** [PiyushKalyanpy/GyanaGuru#394]
### What feature?

add a google map on contact us page .

### Show us the magic with screenshots

[
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/67356946/38cf4bbc-c7c1-4479-9a39-478be4e72c16)
](url)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Humaira-Sadia** [comment]
Hello @PiyushKalyanpy I have good knowledge of React CSS and Javascript, I have previously worked on similar kind of project and I believe this time I can add some more features to it like integrating it with email which will help me learn and develope my skills. I would be very happy to contribute to this project.
Please assign me this issue :)

SCREENSHOT of previous project : 
![map](https://github.com/PiyushKalyanpy/GyanaGuru/assets/107783584/12603b8f-02ed-4120-8af9-fcd4f1725feb)
