### ISSUE TITLE
[Bug]: Hey Serious issues

### ISSUE THREAD

**Issue by Ayushpanditmoto** [PiyushKalyanpy/GyanaGuru#397]
### What bug you encountered?

I am GSSOC 2023 Mentor , But I found you have not added any label ,
please add levels according to guidelines otherwise pr will be not counted
Please use the appropriate labels on the PRs either it can't be counted
gssoc23

level1
level2
level3 

### Show us the trouble with screenshots

See in issues Section

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Hey @Ayushpanditmoto , there is no need of adding labels in issues as the labels are counted from PR for GSSOC.
