### ISSUE TITLE
[Bug]: Email input field is not working

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [PiyushKalyanpy/GyanaGuru#401]
### What bug you encountered?

email field not taking input from user 

### Show us the trouble with screenshots

https://github.com/PiyushKalyanpy/GyanaGuru/assets/112896644/da007534-5200-4778-8fac-c23721b65769

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
That is disabled.
