### ISSUE TITLE
[Feat]: JS validation add on contact form

### ISSUE THREAD

**Issue by Geeta259** [PiyushKalyanpy/GyanaGuru#406]
### What feature?

Add empty validation on contact form
Validation add for valid email
Error message shown below of fields
Highlighted that field by red border to enhance user experience..
Shown success message after submit the form then clear form.
![Screenshot (452)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/75520947/04fcca55-0c1a-4790-8163-8a9fe8a95175)
@PiyushKalyanpy  I would like to contribute on this project under GSSOC'23!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Please don't create a pr before showing us the output.

**Comment by PiyushKalyanpy** [comment]
what are the updates??
