### ISSUE TITLE
[Feat]: Create a FAQ page

### ISSUE THREAD

**Issue by Dev-Ahmadubah** [PiyushKalyanpy/GyanaGuru#407]
### What feature?

Design and add dummy info for the FAQ page, so that when the FAQ is ready it will just be updated.

### Show us the magic with screenshots

![Screenshot (504)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/60859825/c805818b-54a6-4e77-a431-e0cf374faf6a)
![Screenshot (503)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/60859825/81a5b14e-f122-4760-9b2d-fe73aab3bf4e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We will add the issues with the new design in the next 2-3 days.
