### ISSUE TITLE
[Feat]: Scroll to top button

### ISSUE THREAD

**Issue by kaashikaagrawal** [PiyushKalyanpy/GyanaGuru#408]
### What feature?

A scroll to top button that takes the user to the top of the page after scrolling for some time.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by amilali** [comment]
Assign this to me
 I agree to follow this project's Code of Conduct
 I'm a GSSoC'23 contributor
 I want to work on this issue
