### ISSUE TITLE
[Docs]: Add a pull request template

### ISSUE THREAD

**Issue by kartikjoshi267** [PiyushKalyanpy/GyanaGuru#409]
### Description

Till now, there is no pull request template for the repository. I want to add a pull request template for the repository.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We already have a pull request template, but it is not at its right place it is in root folder, would you like to place the file in it right position??

**Comment by kartikjoshi267** [comment]
> We already have a pull request template, but it is not at its right place it is in root folder, would you like to place the file in it right position??

I have raised a new issue regarding this please assign that issue to me
