### ISSUE TITLE
Add Dark Mode Toggle GsSoC'23

### ISSUE THREAD

**Issue by Nikhil1017** [PiyushKalyanpy/GyanaGuru#41]
Add a Dark mode to the Website Triggered by a Toggle Button using Nextjs with Tailwind CSS

**Comment by Sathvik902** [comment]
Hello, please assign it to me. I have been selected as a gssoc contributer.
I can add it. Thank You.

**Comment by Sathvik902** [comment]
Please add GSSOC label to it as I am contributing under gssoc.
Thanks!

**Comment by Nikhil1017** [comment]
Thanks
