### ISSUE TITLE
Add a "Scroll to Top" floating button 

### ISSUE THREAD

**Issue by harshita-kaushik2** [PiyushKalyanpy/GyanaGuru#42]
Hey,
As one can observe from viewing the website, it lacks a scroll-to-top button. Adding this floating button would enhance the user experience of the website.

I'd love to contribute this feature as I have past experience of creating in my personal projects and would request you to assign this issue to me as GSSoC 2023 Contributor.
Thank You :)

**Comment by PiyushKalyanpy** [comment]
What are the updates @harshita-kaushik2

**Comment by PiyushKalyanpy** [comment]
@Swetha-Baskaran what are the updates, are you working on it ??

**Comment by Swetha-Baskaran** [comment]
If you assign me this task I'll work on adding this floating scroll top button feature

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me

**Comment by pushkar-2804** [comment]
Hey @PiyushKalyanpy, I would like to work on this issue. Please assign me under GSSOC'23

**Comment by PiyushKalyanpy** [comment]
> If this enhancement was not done I would like to work on this.

@Swetha-Baskaran I have assigned this issue to you.
