### ISSUE TITLE
[Bug]: Improving UX by scheduling popup visibility to once in a visit

### ISSUE THREAD

**Issue by abhijain1705** [PiyushKalyanpy/GyanaGuru#421]
### What bug you encountered?

why seeing the contributor popup everytime when Homepage mounted

this create bad user experience when someone see the popup everytime user come back to home page from any route.

we can write the logic like to make the popup visible only 1 time for each visit.

for eg. if I visit websit I could see popup first time and now whether I change route or whatever happen I won't see popup again until I close tab

### Show us the trouble with screenshots

![Screenshot 2023-06-27 180939](https://github.com/PiyushKalyanpy/GyanaGuru/assets/137091099/146e2d3e-0f73-40c7-9044-c49b261f2929)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by tausiq2003** [comment]
Can I contribute to this?

**Comment by abhijain1705** [comment]
the contributors might busy somewhere that's why they are not active here
