### ISSUE TITLE
[Bug]: UI fix in the home page

### ISSUE THREAD

**Issue by Shreya111111** [PiyushKalyanpy/GyanaGuru#437]
### What bug you encountered?

Want to add effects(hover effects or other carousel effects) to the home page and change the rectangular border to circular one with border radius for better UI.

### Show us the trouble with screenshots

change border and adding effects to fix the ui
![Screenshot 2023-07-01 180407](https://github.com/PiyushKalyanpy/GyanaGuru/assets/95047638/55c4c1d5-dbf5-4b80-b1bc-b65f1eee65f6)

### Which browsers are affected?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Shreya111111** [comment]
@PiyushKalyanpy  kindly assign the issue to me

**Comment by PiyushKalyanpy** [comment]
Thank you @Shreya111111  for your suggestion, but we have designed it for rectangular blocks only.
