### ISSUE TITLE
[Feat]: FAQ Page and About Us Page

### ISSUE THREAD

**Issue by ojasaklechayt** [PiyushKalyanpy/GyanaGuru#441]
### What feature?

I want to work on FAQ Page and About Us Page. They are very basic. I can improve the design.

### Show us the magic with screenshots:
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/90605717/3258df4a-dd1d-48f9-90a1-5bee8f06fca3)
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/90605717/5ce028e3-2298-40da-be77-92986f55cc09)

After:
About Us Page:
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/90605717/b393b8f7-5bd4-4569-a11b-2b7e47098bcc)

FAQ Page:
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/90605717/26f693fe-7433-4733-b6af-b8960843ac35)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Please show us the design first .

**Comment by ojasaklechayt** [comment]
> Please show us the design first .

@PiyushKalyanpy I have added the design

**Comment by PiyushKalyanpy** [comment]
Hey @ojasaklechayt , thank you for sharing this design with us. While we appreciate your effort, we have decided to explore alternative design options. We will be uploading a new design shortly, and we invite you to work on that instead.

**Comment by ojasaklechayt** [comment]
> Hey @ojasaklechayt , thank you for sharing this design with us. While we appreciate your effort, we have decided to explore alternative design options. We will be uploading a new design shortly, and we invite you to work on that instead. 

Sure 👍
