### ISSUE TITLE
[Bug]: Minor grammatical error

### ISSUE THREAD

**Issue by ShikhaaT44** [PiyushKalyanpy/GyanaGuru#444]
### What bug you encountered?

I found a grammatical error on the home page of the website 
Instead of 'We provides .....' it must be 'We provide ........'.
 Not resolving this error my affect the UX of the website due to such a silly error.

### Show us the trouble with screenshots

![bug1](https://github.com/PiyushKalyanpy/GyanaGuru/assets/89783531/6dd06d8a-112d-4e03-8d58-0012d7d0de99)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Can you make the PR for this by tomorrow?

**Comment by ShikhaaT44** [comment]
Sure I can.
