### ISSUE TITLE
redesigning the about us page. 

### ISSUE THREAD

**Issue by anuza08** [PiyushKalyanpy/GyanaGuru#448]
### What feature?

enhancing about us.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Srishtikumari2002** [comment]
If no one working on this issue so I would like to work on this, I want to enhance the styling of the the about us page as I have a good experience with all the tech stacks mentioned in this project. So, my skills would be helpful in redesigning the about us page again similar to theme of landing page.
