### ISSUE TITLE
enhancing landing page.

### ISSUE THREAD

**Issue by anuza08** [PiyushKalyanpy/GyanaGuru#449]
### What feature?

![Screenshot (82)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/98256478/091a4dfa-1975-41f9-ba9d-e6dd53344229)
removing this part as it looks irrelevant.
![Screenshot (81)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/98256478/cf773db5-cacd-43b4-82bd-f3c0a59a5198)
also improving this part.

please allow me to enhance this part.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We are no more accepting the issues for the landing page.
