### ISSUE TITLE
Adding dummy page for the faq.

### ISSUE THREAD

**Issue by JatinBisht2308** [PiyushKalyanpy/GyanaGuru#45]
Adding a dummy page of fag in it.
We can have a chat regarding the faq page.
Please assign me this issue under gssoc23 as I am a gssoc23 contributor.

**Comment by PiyushKalyanpy** [comment]
Assigning this task to you @JatinBisht2308

**Comment by JatinBisht2308** [comment]
@PiyushKalyanpy thank you please also add the label of gssoc23 in it.

**Comment by rhithesh** [comment]
@PiyushKalyanpy  hi even I would like to work on this thanks under GSSoC23

**Comment by PayalPadmalyaPrusty** [comment]
@PiyushKalyanpy I want to contribute.Please assign me

**Comment by JatinBisht2308** [comment]
> @PiyushKalyanpy I want to contribute.Please assign me

This is assigned to me you can work on another issue.

**Comment by PiyushKalyanpy** [comment]
What are the updates @JatinBisht2308

**Comment by pjyoti121** [comment]
please assign me this issue
