### ISSUE TITLE
[Feat]: Validation add on Contact form to enhance UI

### ISSUE THREAD

**Issue by Geeta259** [PiyushKalyanpy/GyanaGuru#452]
### What feature?

Add empty validation on contact form
Validation add for valid email
Error message shown below of fields
Highlighted that field by red border to enhance user experience..

![Screenshot (544)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/75520947/cee3d081-e3b8-4f37-b9ca-6082f2ab752e)

@PiyushKalyanpy I would like to contribute on this project under GSSOC'23. Please assign this to me.

### Show us the magic with screenshots

here is demo:
![demoform](https://github.com/PiyushKalyanpy/GyanaGuru/assets/75520947/14e3a457-2ad8-4c9f-8474-b950f8befdf6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We are closing this issue as you have created two same issues.
