### ISSUE TITLE
[Feat]: Want to improve the hover effect of the foooter

### ISSUE THREAD

**Issue by HimanshuNarware** [PiyushKalyanpy/GyanaGuru#454]
### What feature?

The hover effect present at the footer is missing left to rignt underline animation effect I want to work on this issue.

### Show us the magic with screenshots

![36](https://github.com/PiyushKalyanpy/GyanaGuru/assets/83147410/18b85e78-1fa7-4749-a264-82e82c079d80)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Hey @HimanshuNarware , we are no more accepting issue on landing page.
