### ISSUE TITLE
Contact Us page should be updated

### ISSUE THREAD

**Issue by whodivyanshu** [PiyushKalyanpy/GyanaGuru#46]
Contact Us page of your website should be updates , it should ask for name , email and the message why the user want to connect

**Comment by whodivyanshu** [comment]
assign me this issue

**Comment by rhithesh** [comment]
@PiyushKalyanpy  can I  also start working on this issue thanks.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.
