### ISSUE TITLE
[Feat]: mode-changing button

### ISSUE THREAD

**Issue by SakshiGoyat** [PiyushKalyanpy/GyanaGuru#471]
### What feature?

The mode-changing button is not working. I want to work on this functionality.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
That button has been disabled due to some bugs.

**Comment by SakshiGoyat** [comment]
okay
