### ISSUE TITLE
[Feat]: dark mode

### ISSUE THREAD

**Issue by Prajwal0225** [PiyushKalyanpy/GyanaGuru#473]
### What feature?

Wanted to add a dark mode feature currently we have only a light mode 

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/103810119/4fa6f80f-f7da-4088-bb22-aef898f7c048)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We have dark mode also but we have disabled it for now, due to some bugs.
