### ISSUE TITLE
The homepage cards are not responsive.

### ISSUE THREAD

**Issue by sudip57** [PiyushKalyanpy/GyanaGuru#474]
### What bug you encountered?

I think there is the issue in the height and width of the card in the mobile device.

### Show us the trouble with screenshots

![Screenshot_2023-07-11-00-44-17-975_com android chrome](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79646606/43cf94bc-aacf-4485-9231-829cf5cc2746)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
I would like to solve this issue .Please assign me this 
Thank you!
