### ISSUE TITLE
[Feat]: Adding dropdown menu for our services

### ISSUE THREAD

**Issue by Priy002** [PiyushKalyanpy/GyanaGuru#475]
### What feature?

Adding a dropdown feature for Our Services; it will enhance the user experience as users can access them directly from navigation bar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Manish12-verma** [comment]
please assign this issue to me

**Comment by Priy002** [comment]
> 

@PiyushKalyanpy
Please assign this issue to me under @GSSOC
