### ISSUE TITLE
[Feat]: make some effect on heading

### ISSUE THREAD

**Issue by dheeraj1129** [PiyushKalyanpy/GyanaGuru#481]
### What feature?

Make some hover color effect on all headings make it "interactive headings"  

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
I would like to hover effect on heading and solve this issue .Please assign me this issue
Thank you!
