### ISSUE TITLE
[Bug]: Dark mode

### ISSUE THREAD

**Issue by Vanoita** [PiyushKalyanpy/GyanaGuru#483]
### What bug you encountered?

Currently, the dark mode button is unresponsive. I would like to add functionality to it.

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/93696376/cd9caa33-0e7a-49a7-9170-2ce1a550e64d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We have disabled dark mode for now due to some bugs.
