### ISSUE TITLE
[Bug]: Align item 

### ISSUE THREAD

**Issue by dheeraj1129** [PiyushKalyanpy/GyanaGuru#487]
### What bug you encountered?

the arrow symbol does not align with the About Us heading 

### Show us the trouble with screenshots

![Screenshot (79)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/72201773/4d4c4bc0-5225-4b96-ad3b-60524e821cdf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Neha626177** [comment]
I want to solve  this  issue please assign me this issue.
Thank You!

**Comment by PiyushKalyanpy** [comment]
Hey  @dheeraj1129  and @Neha626177 , I have added a new issue with the new design for about us page please checkout #489

**Comment by dheeraj1129** [comment]
We can add background color on paragraphs, and add amination to it

**Comment by PiyushKalyanpy** [comment]
Please show us a sample
