### ISSUE TITLE
[Bug]: Light Mode does not work

### ISSUE THREAD

**Issue by dheeraj1129** [PiyushKalyanpy/GyanaGuru#488]
### What bug you encountered?

The Light Mode function does not works

### Show us the trouble with screenshots

![Uploading Screenshot (80).png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We have disabled that for now due to some bugs.
