### ISSUE TITLE
[Feat]: Contact form does not work

### ISSUE THREAD

**Issue by masterboy376** [PiyushKalyanpy/GyanaGuru#492]
### What feature?

User must be able to send messages via contact form and also user messages must be stored in the database.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Hey @masterboy376 , thank you for your suggestion, but we have already implemented that in this project.
