### ISSUE TITLE
[Feat]: To Use src Directory For Improved Code Organization

### ISSUE THREAD

**Issue by s2sharpit** [PiyushKalyanpy/GyanaGuru#497]
### What feature?

I hope this message finds you well. I am writing to raise an issue and propose an enhancement. After careful consideration, I believe that incorporating the feature of Next.js 13, which allows for the addition of an "src" folder, could significantly improve the code organization within our project.

The primary objective of this enhancement is to separate the application code from the project configuration files, which typically reside in the root directory of the project. By adopting this practice, we can achieve better code clarity, maintainability, and ease of collaboration.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Make sure to test the changes and share the screenshot before creating a pull request.
