### ISSUE TITLE
Responsive design 

### ISSUE THREAD

**Issue by Tathagt** [PiyushKalyanpy/GyanaGuru#50]
I will help you make the website responsive for mobile screen. Please let me work on this issue under GSSOC'23.

**Comment by Tushar-sahani** [comment]
I want to work on this issue. please assign this issue to me under GSSOC'23.

**Comment by Tathagt** [comment]
I have my exams going on can I start working on it after 29?

**Comment by amit-does-dev** [comment]
Hi @Tushar-sahani...... I am willing to jump right in....I am excited to contribute to this project and I believe that my skills and experience can be a valuable asset to the team. I am available to start working on the issue right after it will be assigned to me!

**Comment by amit-does-dev** [comment]
Hi @PiyushKalyanpy ...... I am willing to jump right in....I am excited to contribute to this project and I believe that my skills and experience can be a valuable asset to the team. I am available to start working on the issue right after it will be assigned to me!

**Comment by PiyushKalyanpy** [comment]
@lalitmee please check this issue.

**Comment by lalitmee** [comment]
@Tathagt and @Tushar-sahani, can one of you please list all the pages and the effort which will be required to make the application responsive for all the device screens? And then we can divide the work among both of you.

**Comment by Tathagt** [comment]
ok

**Comment by Tathagt** [comment]
![Gssoc](https://github.com/PiyushKalyanpy/GyanaGuru/assets/112072412/6de105b5-ddba-4a93-8f19-0b601b13ae3d)
I am getting this problem
