### ISSUE TITLE
[Feat]: Let user update their profile 

### ISSUE THREAD

**Issue by Akanksha-202** [PiyushKalyanpy/GyanaGuru#508]
### What feature?

Letting users choose the username and profile picture of their choice will enhance the user experience.
Saving this updated profile to Firebase as well, so that the next time the user logs in, the username they changes should be intact! 

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/100708686/e8c90f6e-1263-4dd3-b2b1-334dd15a75d3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Hey @Akanksha-202 , thank you for your interest in our project, we are currently designing the profile page for edit options.
