### ISSUE TITLE
[Bug]: UI Change and Responsiveness Issue in "Why Choose Us" Section

### ISSUE THREAD

**Issue by s2sharpit** [PiyushKalyanpy/GyanaGuru#520]
### What bug you encountered?

Dear @PiyushKalyanpy,

I hope this message finds you well. I am writing to raise an issue regarding the recent UI change in the "Why Choose Us" section on the website. Upon further investigation, it appears that the UI change was introduced in the last commits. Additionally, I have noticed that the section lacks responsiveness on small devices.

## Issue Description

1. **Recent UI Change**: The "Why Choose Us" section on the website has undergone a UI change in the last commits. It is essential to determine whether this change was intentional or accidental to maintain consistency in the website's design and user experience.

2. **Lack of Responsiveness**: Upon testing the website on various small devices such as mobile phones and tablets, I observed that the "Why Choose Us" section does not adapt to smaller screen sizes appropriately. This could potentially lead to a suboptimal user experience for mobile users.

## Proposed Solution

As a concerned user and contributor to this project, I would like to take the initiative to work on resolving these issues. My proposed solution is as follows:

1. **Revert UI Change**: If the recent UI change was unintentional or if there's a general consensus that it negatively impacts the user experience, I am willing to revert the section to its previous state.

2. **Implement Responsiveness**: To address the lack of responsiveness on smaller devices, I propose to implement responsive design principles to ensure that the "Why Choose Us" section adjusts gracefully to different screen sizes and orientations.

### Show us the trouble with screenshots

<img width="200px" src ="https://github.com/PiyushKalyanpy/GyanaGuru/assets/104740281/62dfe816-0dc0-443b-8441-5c04054cdcd4" />

|      Original       |      After last commits       |
| :-----------------: | :----------------: |
| ![Screenshot (481)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/104740281/63835be2-42c5-4bbe-bdc1-357bfacf0e6a) | ![Screenshot (480)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/104740281/18cde3aa-8e9f-41cd-879d-7c6e5023aea3) |

### Which browsers are affected?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [x] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy 
Can you clear about the ui change of section is intentional or accidental. If accidental, I would like to revert the ui of section to its previous state

**Comment by s2sharpit** [comment]
> Hey @PiyushKalyanpy Can you clear about the ui change of section is intentional or accidental. If accidental, I would like to revert the ui of section to its previous state

Hey @PiyushKalyanpy, Can you clear about the above message? It will be helpful to address this issue.

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy 
Kindly clarify about the UI of the section at your earliest convenience.
धन्यवाद

**Comment by PiyushKalyanpy** [comment]
Do not revert it just optimize the new design for mobile screen
