### ISSUE TITLE
[Bug]: Quick links in Home page

### ISSUE THREAD

**Issue by SaiSathvik6** [PiyushKalyanpy/GyanaGuru#521]
### What bug you encountered?

Our services quick link is not working on the home page

### Show us the trouble with screenshots

on clicking our servies:-
<img width="217" alt="image" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/97099124/72fa8982-a32b-49a0-9f06-2c70f247c4c3">

<img width="634" alt="image" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/97099124/70e8d6cf-36d2-4954-be43-407c2925f9a9">

### Which browsers are affected?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by Esha-01** [comment]
@SaiSathvik6 i would like to fix the issue kindly assign this to me under GSSOC 23

**Comment by SaiSathvik6** [comment]
@Esha-01 fix the issue

**Comment by Esha-01** [comment]
@PiyushKalyanpy 
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/98593600/ad15c28d-e274-4248-96a0-a30b2fbeb540)
this issue has already been solved as you tap on the quick links Our services link it takes you to the next page .

I Can solve another issue for you like I can Fix the light to dark theme on the NavBar or else I can create the FAQ page that's the only thing which seems incomplete for now . Look into it once and Assign any of them to me .
