### ISSUE TITLE
[Bug]: Dark Mode on home page

### ISSUE THREAD

**Issue by SaiSathvik6** [PiyushKalyanpy/GyanaGuru#522]
### What bug you encountered?

Dark mode functionality is not working on the page. only light mode is enabled.

### Show us the trouble with screenshots

<img width="263" alt="image" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/97099124/e7d3dd3d-fd6e-408c-965e-8f39f62c1fed">

### Which browsers are affected?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Esha-01** [comment]
hey @SaiSathvik6 i would like to solve this issue and add a dark mode button under Gssoc 23

**Comment by SaiSathvik6** [comment]
In website it still same dark mode is disabled
