### ISSUE TITLE
[Feat]: Add Loading Animation to Page

### ISSUE THREAD

**Issue by Nishitbaria** [PiyushKalyanpy/GyanaGuru#527]
### What feature?

**As a user visiting the website, I often encounter situations where I need to wait for content to load, especially when navigating between different pages or performing resource-intensive actions. Currently, the absence of a loading animation creates a somewhat jarring experience, as I'm unsure whether the page is still loading or if there is an issue.**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Please show us the design and animation for the loading.

**Comment by Nishitbaria** [comment]
You can choose from here:https://cssloaders.github.io/ or any custome one you want,i can integrate any loading animation

**Comment by Nishitbaria** [comment]
@PiyushKalyanpy ,please assign me this issue

**Comment by Nishitbaria** [comment]
@PiyushKalyanpy ,which animation do you want or i should add from my choice?

**Comment by PiyushKalyanpy** [comment]
add any of your choice.
