### ISSUE TITLE
[Bug]: Mobile Resposiveness

### ISSUE THREAD

**Issue by 0rigin-c0de** [PiyushKalyanpy/GyanaGuru#532]
### What bug you encountered?

This is awesome website but not responsive to mobile devices fully as i shown in my screenshot below

### Show us the trouble with screenshots

![Screenshot 2023-07-22 133734](https://github.com/PiyushKalyanpy/GyanaGuru/assets/106311923/510e6cd7-fcb8-4b68-940e-f5139ded5b7c)

### Which browsers are affected?

Firefox, Chrome, Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0rigin-c0de** [comment]
@PiyushKalyanpy Kindly assign it to me under GSSoC'23

**Comment by thezeeshann** [comment]
@PiyushKalyanpy assigned me this issue. I can fix this.
