### ISSUE TITLE
[Feat]: Performance Improvement 

### ISSUE THREAD

**Issue by Nikhil1017** [PiyushKalyanpy/GyanaGuru#534]
### What feature?

Replace existing png images with the same exact images in modern formats such as webp which load faster and occupy less space. Thereby decreasing bundle size.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
This issue was solved earlier but not it is not working. I will check whether it is not merged or what, then assign it to you

**Comment by Nikhil1017** [comment]
Okay
