### ISSUE TITLE
[Feat]: Add a cursor pointer

### ISSUE THREAD

**Issue by khushimarothi** [PiyushKalyanpy/GyanaGuru#540]
### What feature?

In the about us page when hovering on why choose cards. The arrow pointer is not looking good turn it into a cursor pointer.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Those cards are not clickable so we have decided not to update the cursor to a pointer.
