### ISSUE TITLE
[Feat]: add github profile link and author commit history link in contributors page

### ISSUE THREAD

**Issue by Anmol-Baranwal** [PiyushKalyanpy/GyanaGuru#544]
### What feature?

> I will use the fetched data to make two CTA: `GitHub` & `Contributions`

Do let me know if you want me to show number of contributions in the card as well.

### Show us the magic with screenshots

> Current
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/74038190/9a6bb494-ce7e-4c32-94b7-4b7386031fb6)

> Something like this
![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/74038190/3f0c9e55-0dd5-42ac-a709-c8ed1f1d99f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
We have decided not to show that for now.

**Comment by Anmol-Baranwal** [comment]
@PiyushKalyanpy 
Kindly check other issues, and let me know if you need them.
