### ISSUE TITLE
[Bug]: Fix Dark Mode not working

### ISSUE THREAD

**Issue by Nikhil1017** [PiyushKalyanpy/GyanaGuru#547]
### What bug you encountered?

The Dark mode button does not seem to be working now. The fix involves a simple change only in the DarkModeToggle.tsx component. I was able to fix the issue locally.

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115337705/8c110365-db7b-48e4-9be9-898d21061b24)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
Hey @Nikhil1017 , we have disabled this for now because of some issue. #506

**Comment by Nikhil1017** [comment]
okat

**Comment by Nikhil1017** [comment]
@PiyushKalyanpy Can you check this out?
