### ISSUE TITLE
[Bug]: Do not open contributors page in new page 

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#548]
### What bug you encountered?

when we click on our contributor button it will redirect to the contributors page and open that link in a new page, but we want to open that link in the same page. 

### Show us the trouble with screenshots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
@PiyushKalyanpy, Would like to work on this issue under gssoc23. Please assign this to me.
