### ISSUE TITLE
[Feat]: Update the position of Explore now button and add animation

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#549]
### What feature?

place the explore button in the center of the screen at bottom that will be fixed and show a ping animation from Tainwind. 

## FOR BUTTON 
- the button should be fixed in center at bottom of the screen 
- should be responsive in all the screen sizes

## FOR ANIMATION 
 - add a div in the background with  full rounded border-radius
 - then add ping animation to that div.

### Show us the magic with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/23559eec-db36-4eb0-83bf-e28cfd6b0185)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy, I would like to work on it.
