### ISSUE TITLE
[Feat]: Hover effect

### ISSUE THREAD

**Issue by Soulpurr** [PiyushKalyanpy/GyanaGuru#551]
### What feature?

I would like to add a hover effect on the card item in the given screenshot.By hover i mean transition easein kind of thing.
![fffg](https://github.com/PiyushKalyanpy/GyanaGuru/assets/92094765/19ccc5a2-1f2b-4dd8-b249-6c899decd23a)
Pls assign this to me under gssoc23

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Manish12-verma** [comment]
hey ,please assign this issue to me under gssoc'23.
