### ISSUE TITLE
[Bug]: signUp page not found

### ISSUE THREAD

**Issue by Soulpurr** [PiyushKalyanpy/GyanaGuru#552]
### What bug you encountered?

Sign page not found either its not been created or something is wrong with link.
I will fix it anyways.

Pls assign this to me under gssoc23.

### Show us the trouble with screenshots

![sdsdsdsd](https://github.com/PiyushKalyanpy/GyanaGuru/assets/92094765/484e8f15-e859-4cfb-9553-ed809411b99b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
that page has been removed
