### ISSUE TITLE
[Bug]: Pause on hover 

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#554]
### What bug you encountered?

pause this marquee on hover

### Show us the trouble with screenshots

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/eaf12772-e7bf-4b1e-ac13-893cb06cab82)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
@PiyushKalyanpy , I would like to work on it.

**Comment by Nikhil1017** [comment]
@PiyushKalyanpy can you assign me this also?
