### ISSUE TITLE
[Feat]: Add Open Graph meta tags  for link previews on social platforms.

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#555]
### What feature?

Add meta tags for open graphs to show previews on different social media platforms, test them and share the screenshot here in the comments to get approved for the pull request.

Refer to this link for more information on open graph : https://ogp.me/

### Show us the magic with screenshots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSoC'23 contributor
- [ ] I want to work on this issue

**Comment by s2sharpit** [comment]
Hey @PiyushKalyanpy, I would like to work on it.

**Comment by Nikhil1017** [comment]
@PiyushKalyanpy can you assign me this?
