### ISSUE TITLE
Firebase key error - how to resolve this

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#56]
### Discussed in https://github.com/PiyushKalyanpy/GyanaGuru/discussions/54

<div type='discussions-op-text'>

<sup>Originally posted by **PiyushKalyanpy** May 20, 2023</sup>
Contributors are getting this error. This error can be resolved by adding the api key's. but for the contributors is there any easy options to remove this error or anything we can do so that only those contributor will see this those who are contributing in backend part.

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/201ece51-bb3c-4fc3-b17b-293876c6ee0b)
</div>

**Comment by PiyushKalyanpy** [comment]
If you are getting error for Firebase auth API - you can checkout to ```nofirebase``` branch ( for frontend), but for backend you have to generate your own firebase API keys. 
- Go to firebase.com -> create account -> create a new project
- Select web project choose nickname and continue
- copy the API keys and replace them in code

**Comment by saiwali** [comment]
Hello, @PiyushKalyanpy  I would like to work on this issue. Can you assign it to me?

**Comment by rhithesh** [comment]
@PiyushKalyanpy do you think we should have a firebase setup guide.

**Comment by PiyushKalyanpy** [comment]
Ya sure you can work on this issue - @rhithesh @saiwali

**Comment by PiyushKalyanpy** [comment]
What are the updates @rhithesh @saiwali
