### ISSUE TITLE
Modifying css of courses buttons

### ISSUE THREAD

**Issue by Mahikagarg09** [PiyushKalyanpy/GyanaGuru#57]
Modify CSS of buttons under 'GET ALL TYPES OF COURSES' ,under 'OUR SERVICES'.
-Changing background color of each button to make the buttons look more enhanced and attention catching.

Please assign me this issue.

**Comment by rhithesh** [comment]
please assign this to me aswell

**Comment by PiyushKalyanpy** [comment]
- Make sure that the new design should match with the current theme. 
- Use tailwind css only.

**Comment by rhithesh** [comment]
@PiyushKalyanpy  hi I have done the changes please merge my pr thanks.

**Comment by Mahikagarg09** [comment]
can you help me with this error please ..I don't know how to use firebase yet.

FirebaseError: Firebase: Error (auth/invalid-api-key).

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/98404416/d1ceb6ea-1a5b-47bd-96cb-ae1312bd28ae)

**Comment by rhithesh** [comment]
![Screenshot 2023-05-21 094807](https://github.com/PiyushKalyanpy/GyanaGuru/assets/115660976/777cdca2-02d6-4383-8841-081f848ede1c)




you can use this config.

**Comment by rhithesh** [comment]
@PiyushKalyanpy please review my pr.

**Comment by Mahikagarg09** [comment]
made a PR after solving issue..
Coursesbutton css #93

Plwase review it.
