### ISSUE TITLE
[FEAT] Custom Error Page 404

### ISSUE THREAD

**Issue by virajchandra51** [PiyushKalyanpy/GyanaGuru#58]
I will design an Error Page for calls or redirecting to pages which do not exist.

Hello!
I am Viraj Chandra, a proud contributor at GSSoC '23. I would like to the contribute to this project by designing an Error Page for calls or redirecting to pages which do not exist.

Things I will be doing as of now:
- [x]  Designing the error page 404

@PiyushKalyanpy Please Assign me this.

**Comment by PiyushKalyanpy** [comment]
Assigned to @virajchandra51

**Comment by PiyushKalyanpy** [comment]
@virajchandra51 What are the updates??

**Comment by virajchandra51** [comment]
@PiyushKalyanpy on it

**Comment by virajchandra51** [comment]
@PiyushKalyanpy check the PR

**Comment by lalitmee** [comment]
@virajchandra51, don't worry. We will be looking at your PRs. Just add us as the reviewers in your PR.

We would ask you to be patient.

**Comment by PiyushKalyanpy** [comment]
Have you referenced this issue in your pr??

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.
