### ISSUE TITLE
[Feat]: Adding a Contributors list to the website

### ISSUE THREAD

**Issue by Sch476** [PiyushKalyanpy/GyanaGuru#588]
### What feature?

I would like to add a Contributors list to the webpage. A contributors list would have names of all the Contributors who contributed in this project.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by PiyushKalyanpy** [comment]
That page is already added in website.
