### ISSUE TITLE
Form Validation in Login and Signup form

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#6]
## The form should show error if 

1. Email is not in correct form 
2. Password is weak or password length is less than 8
3. Password and confirm password are not same

**Comment by harsh472000** [comment]
@PiyushKalyanpy can you assign this task to me?

**Comment by PayalPadmalyaPrusty** [comment]
@PiyushKalyanpy I want to contribute on this.Please assign me

**Comment by PiyushKalyanpy** [comment]
> @PiyushKalyanpy I want to contribute on this.Please assign me

Thank you for expressing your interest in working on this issue! We appreciate your enthusiasm and willingness to contribute. I have assigned this task to you.
