### ISSUE TITLE
Typo in Header [GSSoC2023]

### ISSUE THREAD

**Issue by Kwamecody** [PiyushKalyanpy/GyanaGuru#61]
Hi there,

Please there is a  spelling in the header.

I will be glad if I can be assigned this task.

I am a contributor to GSSoC2023.

**Comment by PiyushKalyanpy** [comment]
Sure assigning this task.

**Comment by Kwamecody** [comment]
Hello Sir,

Please can you assign this task to someone else? Not familiar with TypeScript.

Sorry for any inconvenience I might have caused.

Thank you.

**Comment by PiyushKalyanpy** [comment]
Ok no problem, you can check for the other issues. Mentors will help you in your contribution.

**Comment by Kwamecody** [comment]
@PiyushKalyanpy  thanks
