### ISSUE TITLE
Adding a guidance questionnaire for visitors

### ISSUE THREAD

**Issue by AbhaBarge** [PiyushKalyanpy/GyanaGuru#62]
As a GSSOC' 23 contributor, I would like to add a questionnaire that will ask new visitors about their interests, strengths and weaknesses anonymously. In the end it will display available content that can help the visitor.  The visitor can then sign-up and access the content as a user.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by PiyushKalyanpy** [comment]
@AbhaBarge are you working on it ?? What are the updates ?
