### ISSUE TITLE
Adding Warning Alerts on Sign Up Page

### ISSUE THREAD

**Issue by Hemant2335** [PiyushKalyanpy/GyanaGuru#65]
On the Sign up page if we left the field empty the signup button doesn't work but it too don't show anything

-> So I can add a Alert if the Fields are Empty

Hereby , I request you to assign me this task under GSSOC'23

Thank you

Attachment 
![Screenshot (56)](https://github.com/PiyushKalyanpy/GyanaGuru/assets/85656999/deb4989a-68d3-44dc-8ad6-28e31d398453)

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by PiyushKalyanpy** [comment]
@Hemant2335  please add these alert in login page too.

**Comment by Hemant2335** [comment]
Ok !
I have opened a new issue
