### ISSUE TITLE
Adding Hover Effects on the cards

### ISSUE THREAD

**Issue by piyushkhurana2019** [PiyushKalyanpy/GyanaGuru#67]
I want to add hover effects on these cards, which will make the website more user interactive and they will want to scroll more.
<img width="1440" alt="Screenshot 2023-05-21 at 11 45 26 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/96003210/7e5985a8-5383-4366-aee8-aedf20ef18b9">

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.
