### ISSUE TITLE
Position issue fixed

### ISSUE THREAD

**Issue by piyushkhurana2019** [PiyushKalyanpy/GyanaGuru#68]
The main text of the website is not properly aligned, i fixed this issue and now its looking perfectly fine, please have a look on before after images

before
<img width="1440" alt="Screenshot 2023-05-21 at 11 49 32 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/96003210/f4b16aa3-3ab3-46b1-8290-3928ba3be8b9">

After

<img width="1440" alt="Screenshot 2023-05-21 at 11 55 22 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/96003210/f13a4a42-7e33-4ba4-adc4-83a15aedc699">

Before

<img width="1440" alt="Screenshot 2023-05-21 at 11 50 11 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/96003210/1555f7ff-471d-41b3-9acc-484785b5d046">

After

<img width="1440" alt="Screenshot 2023-05-21 at 11 49 15 AM" src="https://github.com/PiyushKalyanpy/GyanaGuru/assets/96003210/d7ff5c6c-714b-4647-86b3-02aeacd86633">

**Comment by PiyushKalyanpy** [comment]
Ok you can create a PR. 
Make sure not to include package files in pr
