### ISSUE TITLE
update: FAQ section

### ISSUE THREAD

**Issue by SINJINI-G** [PiyushKalyanpy/GyanaGuru#71]
I will add the FAQ component in the QnA format.. Can I work on this issue for gssoc?

**Comment by Rakesh-indupuri** [comment]
I also want to add the FAQ in the Q/A in the json file. I want to work on this for gssoc . could you please assign this to me

**Comment by Rakesh-indupuri** [comment]
I also want to add the FAQ in the Q/A in the json file. I want to work on this for gssoc . could you please assign this to me

**Comment by khushi767** [comment]
Please assign me this issue under GSSOC'23

**Comment by PiyushKalyanpy** [comment]
@SINJINI-G are you working on it ??

**Comment by SINJINI-G** [comment]
Yes @PiyushKalyanpy, I am working on it.. will make a PR soon.. I have a small doubt regarding which I have messaged you on discord. Kindly check.

**Comment by vk20july** [comment]
@PiyushKalyanpy sir i want to work on this issue under gssoc'23

**Comment by Kushagra102** [comment]
hey @PiyushKalyanpy  I am interested in working in this issue. I will implement beautiful accordions for it.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.

**Comment by Kushagra102** [comment]
Hey @PiyushKalyanpy I am interested in working on this issue if you still want the page.
