### ISSUE TITLE
Adding Hover effect on Explore courses button

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [PiyushKalyanpy/GyanaGuru#79]
Please assing it to me under GSSOC'23.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by shreyal0007** [comment]
Please assign this task to me under the GSSOC 2023.

**Comment by afeefuddin** [comment]
hey @PiyushKalyanpy , is this issue still open. Can you assign this to me if @shreyal0007 is not working anymore on this issue

**Comment by afeefuddin** [comment]
Thanks @PiyushKalyanpy . Will be working on it

**Comment by PiyushKalyanpy** [comment]
What are the updates @afeefuddin

**Comment by afeefuddin** [comment]
hey @PiyushKalyanpy , working on it. Neeed some time

**Comment by afeefuddin** [comment]
I am getting firebase error , and unable to run it locally.. What should i do??
