### ISSUE TITLE
Correcting grammatical and spelling mistakes

### ISSUE THREAD

**Issue by KhushiKhandelwal610** [PiyushKalyanpy/GyanaGuru#80]
I saw some spelling mistakes. Please assign this issue to me under GSSOC'23

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by shreyal0007** [comment]
I want to work on this issue kindly assign me this.
