### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by shruti8302** [PiyushKalyanpy/GyanaGuru#81]
Hey @PiyushKalyanpy,
As a part of GSSOC'23, I would like to improve the footer section of the website by centering the content to make it look better. Kindly assign me this issue.

**Comment by 000626574705** [comment]
hello , i want to work on this issue please assign me

**Comment by PiyushKalyanpy** [comment]
The Footer section is updated, please check if you can make some changes there. I will assign it to you @shruti8302 @000626574705

**Comment by shruti8302** [comment]
Yes @PiyushKalyanpy I can make some changes in the footer section if you will assign it to me.

**Comment by PiyushKalyanpy** [comment]
What changes would you like to do? @shruti8302

**Comment by shruti8302** [comment]
@PiyushKalyanpy I want to change the background color of the footer section. Also I want to change the alignment of Gyan Guru logo and copyright content to make it look clean.

**Comment by PayalPadmalyaPrusty** [comment]
@PiyushKalyanpy I want to contribute.Please assign me
