### ISSUE TITLE
Hover Effect on Navbar

### ISSUE THREAD

**Issue by kartikayasija** [PiyushKalyanpy/GyanaGuru#84]
Please assign me this issue under Gssoc'23.

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by 000626574705** [comment]
i want to work on it plz assign me that

**Comment by shreyal0007** [comment]
I want to work on this issue . kindly assign me this under GSSOC 2023.
