### ISSUE TITLE
Enable lazy loading to improve website performance

### ISSUE THREAD

**Issue by M-A-N-I-K** [PiyushKalyanpy/GyanaGuru#85]
Lazy loading is a technique that can be used to improve the performance of a website by delaying the loading of images and other resources until they are needed. This can help to reduce the initial load time of a page, which can improve the user experience and make the website more responsive.

The benefits of lazy loading include:

-     Reduced initial load time
-     Improved user experience
-     More responsive website
-     Increased SEO ranking

**Comment by rhithesh** [comment]
i would like to work on this issue Thanks.

**Comment by M-A-N-I-K** [comment]
I raised this issue so i would like to work on this by myself!

**Comment by PiyushKalyanpy** [comment]
Sure i am assigning this to you @M-A-N-I-K

**Comment by PiyushKalyanpy** [comment]
What are the updates??

**Comment by sumitkr2000** [comment]
Hey, @PiyushKalyanpy Can I work on this issue? I have experience in implementing lazy loading to the website. Please assign me this issue. It seems that he is not active.

**Comment by Kushagra102** [comment]
Hey @PiyushKalyanpy I would like to work on this issue. I too have experience with implementing lazy loading on the web-apps.

**Comment by PiyushKalyanpy** [comment]
We are closing this issue because it has been inactive for a long time.

**Comment by sumitkr2000** [comment]
@PiyushKalyanpy please assign me this issue
