### ISSUE TITLE
Making Component : Course Card

### ISSUE THREAD

**Issue by PiyushKalyanpy** [PiyushKalyanpy/GyanaGuru#96]
Make sure : 
- push only required files ( do not push package , gitignore or other unnecessary files)
- Make sure to stick to the simple theme design.

![Slice 1](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/8dad66ea-aa87-4ea3-bc8a-b73ab6f85a97)

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/2c449811-ba30-4db5-b31d-19626d193e57)

**Comment by Jyotipal29** [comment]
i want to work on this issue please assign to me

**Comment by shreyal0007** [comment]
I want to make this course card UI kindly assign it to me .

**Comment by PiyushKalyanpy** [comment]
These are the sidebar components

![image](https://github.com/PiyushKalyanpy/GyanaGuru/assets/79275157/794a7053-c382-4256-9b0a-8d2493ac3a90)

**Comment by AnkitAnandMastery17** [comment]
Can I also work on this as a GSSOC contributor?

**Comment by Lobi29** [comment]
**Okay I am working on your Course Card component 👍🏻**

**Comment by shreyal0007** [comment]
@PiyushKalyanpy which part of the card am i suppose to  make

**Comment by bhoomikhurana** [comment]
I'd like to work upon this issue if this hasn't been done yet.Pls assign it to me.I have a good knowledge of UI as well as React
