### ISSUE TITLE
[Feat]: Implement login with Google

### ISSUE THREAD

**Issue by subrat611** [PiyushKalyanpy/GyanaGuru#99]
Could you please assign this issue to me?

**Comment by shreyal0007** [comment]
I want to implement this feature . Kindly assign me this under GSSOC 2023.

**Comment by subrat611** [comment]
Hey, @PiyushKalyanpy there is no Firebase config/global file did I have to create one?

**Comment by PayalPadmalyaPrusty** [comment]
@PiyushKalyanpy I want to contribute.Please assign me
